---
networks:
  apps:
    name: apps
    external: true
services:
  forgejo:
    container_name: forgejo
    environment:
      - USER_UID=568
      - USER_GID=568
    image: codeberg.org/forgejo/forgejo:14
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.forgejo.rule=Host(`git.aresu.eu`)"
      - "traefik.http.routers.forgejo.entrypoints=websecure"
      - "traefik.http.routers.forgejo.tls=true"
      - "traefik.http.services.forgejo.loadbalancer.server.port=3000" # Internal port of Forgejo web server
    networks:
      - apps
    ports:
      - 3000:3000 # Shouldn't be needed with traefik
      - 222:22
    restart: unless-stopped
    volumes:
      - /mnt/tank/apps/forgejo:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
