---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/monitoring.coreos.com/alertmanagerconfig_v1alpha1.json
apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: alertmanager
spec:
  route:
    groupBy:
      - "alertname"
      - "job"
    groupInterval: 10m
    groupWait: 1m
    receiver: discord
    repeatInterval: 12h
    routes:
      - receiver: "null"
        matchers:
          - name: alertname
            value: Watchdog
            matchType: =
      - receiver: "null"
        matchers:
          - name: alertname
            value: InfoInhibitor
            matchType: =
      - receiver: discord
        matchers:
          - name: severity
            value: critical
            matchType: =
  inhibitRules:
    - equal:
        - "alertname"
        - "namespace"
      sourceMatch:
        - name: severity
          value: critical
          matchType: =
      targetMatch:
        - name: severity
          value: warning
          matchType: =
  receivers:
    - name: "null"
    - name: "discord"
      discordConfigs:
        - apiURL:
            key: discord_webhook_url
            name: alertmanager-secret
          username: AlertManager
          title: |-
            [{{ .Status | toUpper }}{{ if eq .Status "firing" }}:{{ .Alerts.Firing | len }}{{ end }}] {{ .CommonLabels.alertname }}
          message: |-
            {{- range .Alerts }}
            {{- if ne .Labels.severity "" }}
            **Severity:** _{{ .Labels.severity }}_

            {{- else }}
            **Severity:** _N/A_

            {{- end }}
            {{- if ne .Annotations.description "" }}
            **Description:** _{{ .Annotations.description }}_

            {{- else if ne .Annotations.summary "" }}
            **Summary:** _{{ .Annotations.summary }}_

            {{- else if ne .Annotations.message "" }}
            **Message:** _{{ .Annotations.message }}_

            {{- else }}
            **Description:** _N/A_

            {{- end }}
            {{- if gt (len .Labels.SortedPairs) 0 }}
            **Details:**

            {{- range .Labels.SortedPairs }}
            * **{{ .Name }}:** _{{ .Value }}_

            {{- end }}
            {{- end }}
            {{- end }}
