---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: blackbox-exporter
spec:
  interval: 30m
  chart:
    spec:
      chart: prometheus-blackbox-exporter
      version: 9.2.0
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
      interval: 30m
  values:
    fullnameOverride: blackbox-exporter

    image:
      registry: quay.io

    podSecurityContext:
      sysctls:
        - name: net.ipv4.ping_group_range
          value: "0 2147483647"

    config:
      modules:
        http_2xx:
          prober: http
          timeout: 5s
          http:
            valid_http_versions: ["HTTP/1.1", "HTTP/2.0"]
            follow_redirects: true
            preferred_ip_protocol: "ip4"
        icmp:
          prober: icmp
          timeout: 30s
          icmp:
            preferred_ip_protocol: "ip4"

    ingress:
      enabled: true
      className: internal-nginx
      annotations:
        external-dns.alpha.kubernetes.io/target: &hostname "ingress-int.${SECRET_DOMAIN}"
      hosts:
        - host: "{{ .Release.Name }}.${SECRET_DOMAIN}"
          paths:
            - path: /
              pathType: Prefix

    prometheusRule:
      enabled: true
      additionalLabels:
        app: prometheus-operator
        release: prometheus
      rules:
        - alert: BlackboxSslCertificateWillExpireSoon
          expr: probe_ssl_earliest_cert_expiry - time() < 86400 * 3
          for: 15m
          labels:
            severity: critical
          annotations:
            summary: |-
              The SSL certificate for {{ $labels.target }} will expire in less than 3 days
        - alert: BlackboxSslCertificateExpired
          expr: probe_ssl_earliest_cert_expiry - time() <= 0
          for: 15m
          labels:
            severity: critical
          annotations:
            summary: |-
              The SSL certificate for {{ $labels.target }} has expired
        - alert: BlackboxProbeFailed
          expr: probe_success == 0
          for: 15m
          labels:
            severity: critical
          annotations:
            summary: |-
              The host {{ $labels.instance }} is currently unreachable

    pspEnabled: false

    securityContext:
      readOnlyRootFilesystem: true
      allowPrivilegeEscalation: false
      capabilities:
        add: ["NET_RAW"]

    serviceMonitor:
      enabled: true
      defaults:
        labels:
          release: prometheus
        interval: 1m
        scrapeTimeout: 30s
      targets:
        # TrueNAS
        - module: http_2xx
          name: truenas-http
          url: "http://truenas.${SECRET_DOMAIN}"
        - module: icmp
          name: truenas-icmp
          url: "truenas.${SECRET_DOMAIN}"

        # Unraid
        - module: http_2xx
          name: unraid-http
          url: "http://unraid.${SECRET_DOMAIN}"
        - module: icmp
          name: unraid-icmp
          url: "unraid.${SECRET_DOMAIN}"

        # NodeProxyManager
        - module: http_2xx
          name: npm-http
          url: "http://npm.${SECRET_DOMAIN}"
        - module: icmp
          name: npm-icmp
          url: "npm.${SECRET_DOMAIN}"

        # HomeAssistant
        - module: http_2xx
          name: homeassistant-http
          url: "http://10.17.1.4:8123"
        - module: icmp
          name: homeassistant-icmp
          url: "10.17.1.4"

        - module: icmp
          name: ping-cloudflare
          url: 1.1.1.1
          scrape_interval: 30s
