[env]
JUST_UNSTABLE = "1"
FLATE_PATH = '{{config_root}}/kubernetes/flux/cluster'
KUBECONFIG = '{{config_root}}/kubeconfig'
MINIJINJA_CONFIG_FILE = "{{config_root}}/.minijinja.toml"
TALOSCONFIG = '{{config_root}}/talosconfig'

[hooks]
postinstall = "ansible-galaxy install -r {{config_root}}/ansible/requirements.yaml"

[plugins]
krew="https://github.com/soupglasses/mise-krew"

[settings]
pipx.uvx = true

[tools]
actionlint = "latest"
ansible = "latest"
ansible-core = "latest"
flux2 = "latest"
gum = "latest"
helm = "latest"
helmfile = "latest"
just = "latest"
k9s = "latest"
kubectl = "latest"
pipx = "latest"
talosctl = "latest"
task = "latest"
terraform = "latest"
uv = "latest"
yamlfmt = "latest"

"aqua:cilium/hubble" = "latest"
"aqua:kubernetes-sigs/krew" = "latest"
"aqua:mitsuhiko/minijinja" = "latest"
"github:home-operations/flate" = "latest"
"github:kguardian-dev/kguardian" = { version = "latest", version_prefix = "advisor/v", exe = "advisor", bin = "kubectl-kguardian" }
"krew:browse-pvc"="latest"
"krew:cnpg"="latest"
