[settings]
pipx_uvx = true

[env]
# Kubernetes
KUBECONFIG = '{{config_root}}/kubernetes/kubeconfig'
TALOSCONFIG = '{{config_root}}/kubernetes/talos/clusterconfig/talosconfig'

[tools]
"aqua:astral-sh/uv" = ["latest"]
"pipx:flux-local" = ["7.5.6"]
"aqua:go-task/task" = "3.44.0"
"aqua:siderolabs/talos" = "1.10.3"
"aqua:budimanjojo/talhelper" = "3.0.29"
"aqua:cloudflare/cloudflared" = "2025.6.1"
"aqua:FiloSottile/age" = "1.2.1"
"aqua:fluxcd/flux2" = "2.6.2"
"aqua:getsops/sops" = "3.10.2"
"aqua:helm/helm" = "3.18.3"
"aqua:helmfile/helmfile" = "1.1.2"
"aqua:jqlang/jq" = "1.7.1"
"aqua:kubernetes-sigs/kustomize" = "5.6.0"
"aqua:kubernetes/kubectl" = "1.33.0"
"aqua:mikefarah/yq" = "4.45.4"
"aqua:yannh/kubeconform" = "0.7.0"
