[settings]
pipx_uvx = true

[env]
# Kubernetes
KUBECONFIG = '{{config_root}}/kubernetes/kubeconfig'
TALOSCONFIG = '{{config_root}}/kubernetes/talos/clusterconfig/talosconfig'

[tools]
"aqua:astral-sh/uv" = ["latest"]
"pipx:flux-local" = ["7.0.0"]
"aqua:go-task/task" = "3.41.0"
"aqua:siderolabs/talos" = "1.9.4"
"aqua:budimanjojo/talhelper" = "3.0.19"
"aqua:cloudflare/cloudflared" = "2025.2.0"
"aqua:FiloSottile/age" = "1.2.1"
"aqua:fluxcd/flux2" = "2.4.0"
"aqua:getsops/sops" = "3.9.4"
"aqua:helm/helm" = "3.17.1"
"aqua:helmfile/helmfile" = "0.171.0"
"aqua:jqlang/jq" = "1.7.1"
"aqua:kubernetes-sigs/kustomize" = "5.6.0"
"aqua:kubernetes/kubectl" = "1.32.2"
"aqua:mikefarah/yq" = "4.45.1"
"aqua:yannh/kubeconform" = "0.6.7"
