[settings]
pipx_uvx = true

[env]
# Kubernetes
KUBECONFIG = '{{config_root}}/kubernetes/kubeconfig'
TALOSCONFIG = '{{config_root}}/kubernetes/talos/talosconfig'

[tools]
"aqua:astral-sh/uv" = ["latest"]
"pipx:flux-local" = ["7.8.0"]
"aqua:go-task/task" = "3.44.1"
"aqua:siderolabs/talos" = "1.10.7"
"aqua:budimanjojo/talhelper" = "3.0.34"
"aqua:cloudflare/cloudflared" = "2025.8.1"
"aqua:FiloSottile/age" = "1.2.1"
"aqua:fluxcd/flux2" = "2.6.4"
"aqua:getsops/sops" = "3.10.2"
"aqua:helm/helm" = "3.18.6"
"aqua:helmfile/helmfile" = "1.1.6"
"aqua:jqlang/jq" = "1.8.1"
"aqua:kubernetes-sigs/kustomize" = "5.7.1"
"aqua:kubernetes/kubectl" = "1.33.3"
"aqua:mikefarah/yq" = "4.47.1"
"aqua:yannh/kubeconform" = "0.7.0"
