apiVersion: v1
kind: Secret
metadata:
    name: minio-secret
stringData:
    MINIO_ROOT_USER: ENC[AES256_GCM,data:zKb40gtzsm6yBg==,iv:UUbukb6USKehbdBsPY4ZUxJtmLjK4RgOw7h9sTbcXis=,tag:/d/Rl2nIQpMdHvYim/zERw==,type:str]
    MINIO_ROOT_PASSWORD: ENC[AES256_GCM,data:MzhH7dZvcCtD++0HFSRqkV453SU=,iv:stpJic0/Qa6SjBWXr7afMXckCJRT3ezPyofO0d1GT/g=,tag:vCtUQvrPQiefWUP49FRc4g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19ufzusf8ls394p4kl5498myl24w7x6ggc5w9grq4tk8dcyh709ls6ku97r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuUlJrVnhrVGZpUjlCV3hJ
            MGVkWjhRaDllcjVsdmZzVFdlNU42TTVoU0M4CnJueUVBQWdiUnRTOEhWWEsrYWli
            SmdWYlVwQ1JDUC85Yng0KzBOWkxzSWcKLS0tIGExMmZhd0FjSitxMDhsR2Zmb2Fo
            NmhSOVp0djVwVEY5eG5pWjhyTGtqV00KjwJOZ6D3GEbIAQmJEdWWoORZkioK3F3B
            1M0fMsMew2baN8EvGYvhCe7HyMRe5I+UkBWuJd1Zeg682e+VeRUDLA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-04-23T17:17:58Z"
    mac: ENC[AES256_GCM,data:6ALYlxYXg+vzJgB8f/tNziclBimAkY2t8dwD15nkoC8XrQgedWFJhuoWh32R2kqH4x8TfcGCkd/CSy6h7RMLeFxOMbBQgQxN18s7JIyjt7BCwnXTzVKhGdS/J/2vfifqe9waZop0EmqK+XR7XDBQ73ws5apQ1bGBT2iow6Bp+AU=,iv:1jrmJJQg5DUd2H94cjuVFrKYMiRFDNPwxsB2sSVDyjo=,tag:qjSvsltBQ78XcomQyi5pHA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
