apiVersion: v1
kind: Secret
metadata:
    name: nextcloud-secret
stringData:
    nextcloud-username: ENC[AES256_GCM,data:tyYI7v0=,iv:UNpYE2f6GnL2gwBmTvEmK2Jix5LjGvpKXGp/vDAC2uI=,tag:ahKhygK4MB9CzAgEbzWrJw==,type:str]
    nextcloud-password: ENC[AES256_GCM,data:XEucoCRSM3Oz21A0j3VpAQUGN8Q=,iv:d+ufyYG3jIlv2MtgdgfLvC+8CAuxHPNoyWujzOzvP28=,tag:qgC1uwKWfPahrOdMcbJ94g==,type:str]
    smtp-host: ENC[AES256_GCM,data:XbyVT3qzvcfumi15+kU=,iv:CKsGKmVautWw1n6Jjn6d9zZQh7CgYgSVorxr/E24vrE=,tag:ZclAlLRGwjVDFQfFLzMEjA==,type:str]
    smtp-username: ENC[AES256_GCM,data:L4MmuuT17bl1YZVYIzVpU9cXgf1fVYq7kg==,iv:FqqS46/SEquAjY5+I9wGe2DKtlvhTROxUgIGT66qL+8=,tag:kYgD66oCoYQ/8H9Ex4vJ3A==,type:str]
    smtp-password: ENC[AES256_GCM,data:rTAfPmEGLpUIUHjIRZtzjA==,iv:tzYQujYCpBOlDCwKNOWMae9tG2bqxLGjKpabTHxQLKA=,tag:3KD7j06tj3l1w31dErVOFw==,type:str]
    db-username: ENC[AES256_GCM,data:zgn4sKupiTT9,iv:QBGB9p9Pg0eVi4Pk1jja5AZSw+E8+UM2tNI8emcW1Fc=,tag:gTxrV4ZkgW3PV3RfTjPLRg==,type:str]
    db-password: ENC[AES256_GCM,data:K6SAI892FRuZQp7U6v8PSX9wUCU=,iv:IEzEXzILhMRqwMm3E6ka2D2ZkpSHnVxAEwlP86XwUGY=,tag:ey4qvkUi2GaL3t4haENpow==,type:str]
    password-salt: ENC[AES256_GCM,data:3k/pQWMTQU3bhb5Jwz7No1TxqcBsarCsI0/7RBQW,iv:JB76Fn6xb1gTSYrIoijDVHcW4kArG9ovd//BWvDWAZ4=,tag:jULDTZEUUOb+6TpB7oTHhQ==,type:str]
    secret: ENC[AES256_GCM,data:ISjzG1xFlR/gLdLz+aVMX0TzYSLtck4EbtprPihUM7nJMcuiRkwgZeLoP9tvp5AA,iv:LC6n59HHaBCDC6eP3ghtQJZq4yEvuXbAkKzjFIYujrU=,tag:68Yprj6xkpvZU7ISIwZhWQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19ufzusf8ls394p4kl5498myl24w7x6ggc5w9grq4tk8dcyh709ls6ku97r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnd0NrZVFIeitETENFOVRp
            a2txRXhPc2Q5MVE0NnNsenhWMFAwNVpFbVRvClE3V25JRjdrRUdRYzVubVo2QldU
            Qms3YkNhL0sxNzY4RUluYXM1ZG0yWWsKLS0tIEV4M0FuUlh1aDBsMzN0OGZEMDFj
            Sm0vd1lOSkNmemVlRFNWK2VOcUNqVzQKvJUmTA23thBOYW3tMY7QwpaFPW+Su/t3
            8Tcim5b+IywF1ubQCQmecQff4Z/bLp4kuRsTs3447jhorFQr+FNjTQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-05-17T18:05:13Z"
    mac: ENC[AES256_GCM,data:XkK6WkhJ15JwwT5QGENeKpZz0rNU/t0HZ8Mxc9twKRUXWTT4Qbm+8tuHimvSUK+I2a0SZYPo8nits6Skur9jz0LscUkE/sxGluBo77tMcBy3kvG7yohiwQGCEb2gTBP99w8yfRNSIgV2ZKkLwPAheZ0jxurEL/xJmc2tO0ASu3s=,iv:Nmzfei79zUcNNDzoavXrZeetBEn46f1PK5w900DGUZ4=,tag:8zmcI4vZotLzeHAaBHJANA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
