---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: transmission-config-v1
  annotations:
    helm.sh/resource-policy: "keep"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Mi
  storageClassName: longhorn-replicated
  volumeMode: Filesystem
