apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:ooLR34vfowqTOJd0FnHXOL1gqTdYe4Q+wgLehrgm2mrH89Aq,iv:aex2zNO/eaeaa2z1ycvBCU/71awI0vsATUKgEVweWds=,tag:tAJBCjFqpkGRgOKJuSOqPQ==,type:str]
    credentials.json: ENC[AES256_GCM,data:3eQqIuq8Gn8tOhRZ+byj/VWPZJkaItbf7ek56EvEV8+Ptm7Kbx8H0J4wBh9+QKecGA3+CsTKcY8c1iA3fJDluYsrimWHPJZPlGlb4qY3S6/cT+bPvdDjtoRzQtFZiteixrkX5w2cst5Bk689S+p4XIzLXq15kiM0A+zP2IHzs6MUnMDh2pEjuXWhWl4AHfgEQo+7MBK7UHhoJ/OIpLBXHI82h3FbBeoTp6WvP0eXVw==,iv:4IpaSPgawwys7/njLEXjo8zvA52sL6p7Nv9W5PyQFRU=,tag:xx2J/CmPly8D6v94gp+VUA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19ufzusf8ls394p4kl5498myl24w7x6ggc5w9grq4tk8dcyh709ls6ku97r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxQ3M5bEcxZHVWQW1Ra1N2
            eE5CNmVoaGxqRkdmRkpQQ3BzeFpNd2RGaHlzCjRwSVo1aUdTRG90eDFYSXpSaUZo
            WkdPYTI0eXZKRlNieS8vRjNrekRkYzAKLS0tIDllN0E4d2lFWFdTcmVJV0kzTjBR
            c0xWanA4dUxFL1B5N0RrN0NMUzlrencKOvgCGvLFI/7x5rfJOjhejr+bUfsuEJCX
            s6iOfEVvyy4fy1waXQKsG44LR1sFspi1emVCcDJMUUapQz3VvyIUsw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-04-14T13:33:05Z"
    mac: ENC[AES256_GCM,data:/Gxu/i6qsLtWQ2Sb7Mx7ZFWq3ETr9je/EzmI1hVXhsOTndXQa3Ns3V3hWAv6r6fykOy2ESI1ZQsFISVN9EUxHTd90vi/bbunDXwi2qLqNAy6QlS50jAQwm2o1nQPe6PMr2kqJ2wVPA9xsC1B1GhjMuCss/CvBRYbR0vK2g4sFGY=,iv:Aud+f3Q5lw2vmSTumEKuatfJDyd52vXyNW3EVkq9+n8=,tag:3CVneD6cKNida8mKNtSVEQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
