apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:bEB81gst+1TC9cNCL11us3Zzm2jLO77/G785Wr+y1vkbPyIt,iv:kTqKN8S1AMJ8o0pQ85fkJ/CSJawWs6t5GCqM+FNXacs=,tag:0mat79qiJ0nlL0oT6PvJdA==,type:str]
    credentials.json: ENC[AES256_GCM,data:Rb/2gnRT4ZEHsir7X6gzKVmRe457Qp4ZPQhZWknK7X/SPiaejZgxhRpeeuFxTjZPnCLZYS1ZI2GOuCUM+sJzb5aTVmhFyyswT2PyEW/AuVN5fhmftc0yvrdmP0/RyJWZnH+VChfjM9MdWb16P86dKmL2Rg/VeCURLxx+hf52/SyBtJZR4nCe81c5Z+Ga0KrwE2lcLXhPB/BZBl2pw+u/uH/irA==,iv:M1hgJ74a/ZxrUk0+se1KBOVbnrdr1HhvWcu3iU8rEHw=,tag:wZhxADEFOAcJbpTahnOFCg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19ufzusf8ls394p4kl5498myl24w7x6ggc5w9grq4tk8dcyh709ls6ku97r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjZ2FQK1liR3RGbVM0RHly
            ekp0VzNjWUpjcWJYSkNwQ2JYdUJ1MXJaRGhFClFNeUd5d29UWkdWSXFBNzZ1aFBk
            czB5aGZ0ektRTk9MM2FJWGo4ZzRGZUUKLS0tIHlLS09wU2JvcUlRWU92aDJaR3Iy
            RjgvU05JL0V2UUtTaE9zOEl1VWhEV2MK/pxwgvdRz8ZNUr5L81EXrHj6hn2f4OrV
            tuNIfaEladSm+F24KUUN2SsjZ7FcSfuWYoXHIgBIONN6jthWf7fbng==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-04-14T10:21:12Z"
    mac: ENC[AES256_GCM,data:S09rk/E15QCpE/RtfTfaGRVBAhpE4+TFa5hqn158Cp8pJ7cA0s0QdGQJaQmR3TncpMgGPLp3BcQ1R6DdHj/JtqK+ktWS4YASTS7CTqW/8unQkYRHaxWzbH2OwzmDfTbqDAKfDdyChOWvaOAe5NDzChrKIENr9uTuXGKGEwzP9jE=,iv:JSSHSpmXh9w0lfr3bx/mbkUlgTlqROOxmvHl/GiSaAY=,tag:9ksFIUgVVLHiEB7cG8S8TQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
