apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:/iFcP8JSW7/zZPopwWmzrkkovOk6/0vVdH/D7/b2VKNley6W,iv:zidUmzoYoW7CUA9n03CTgdGvTvQNhX6uo4y1lJgLYd0=,tag:ffQFF0L4e4vWe438Q76jeA==,type:str]
    credentials.json: ENC[AES256_GCM,data:7iP52o8kZmUhRua5aBoy1O7bleYabsmgFLwOWfsj3aqo+K6ZllQ66xNt/A+hvp8P4mhwxlgqqJsuvOJCDdi4qNOVkG0scDQSOBImQOhGjjdlscNDTn90kMk6zKys46psthFtshOgPLLfAIkENE70eDn1vdsI6qwH8Rhf4vXkk26GItMUa40ESJjK7Q4gniLt0ZAfqPWegNnc1QLc0Tu34RJDjkQD4hItJvoqqtO93A==,iv:E3SgC7uDyY21obgH9BbgC0R7xHomZjN4sGDIC1LWBqE=,tag:viXrPg0lNvHTTb4JoJryJg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19ufzusf8ls394p4kl5498myl24w7x6ggc5w9grq4tk8dcyh709ls6ku97r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDSTl2TmVPZUozRjJ2Qzh5
            ZElKQm1DTzVxYzc4cCtXaTRINnhrNUIxMEhnCkFxLzFZclpUbTk1dlRmWUZOMnFk
            N1FXMlc1cTI0dnNYb3NQWVEvbmMvMnMKLS0tIDNLNm0wV2JwaW5ra2R0L0xUbFVy
            c1hOUmt6cjc5RHEyNHRlc0tnUHc1TmcKNQtW8KVNq82PuQPpThxktj8QIxLnbVuO
            pN/SJ1e02EtpjMOtSdY8wmwC+dUdj/pI/v/v7nazO6LC1BCKkO668g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-04-14T22:37:52Z"
    mac: ENC[AES256_GCM,data:UoLvz1AHp4IQvwlcZfszyC8lP6xsYxMTyp9iRoJCVyTxFeI8my7oRuGpUY+jX3bhjBc8SpsuSwb16s3f9GL3liXxNWgeuFAH2yJVMAy4+xZcXcaGHaGWLnw0dPamvvzzBLu6ZjWrJQIimAbtMgYlyn0NyDIoPkC2K6p7p4LWWZw=,iv:Ee2gwsOYqafFRMWG8rr7Qtyi5wygWfhq0uD2oJRH/O0=,tag:JKN7Cs65SuSJBy2ny9N/aQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
