---
# yaml-language-server: $schema=https://k8s-schemas.bjw-s.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name crunchy-postgres
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: crunchy-postgres-secret
    template:
      data:
        s3.conf: |
          [global]
        encryption.conf: |
          [global]
  #       s3.conf: |
  #         [global]
  #         repo1-s3-key={{ .minio_crunchy_postgres_access_key }}
  #         repo1-s3-key-secret={{ .minio_crunchy_postgres_secret_key }}
  #         repo2-s3-key={{ .cloudflare_cpgo_access_id }}
  #         repo2-s3-key-secret={{ .cloudflare_cpgo_access_key }}
  #       encryption.conf: |
  #         [global]
  #         repo1-cipher-pass={{ .crunchy_postgres_backup_encryption_cipher }}
  #         repo2-cipher-pass={{ .crunchy_postgres_backup_encryption_cipher }}
  # dataFrom:
  #   - extract:
  #       key: crunchy-postgres
  #     rewrite:
  #       - regexp:
  #           source: "(.*)"
  #           target: "crunchy_postgres_$1"
  #   - extract:
  #       key: minio
  #     rewrite:
  #       - regexp:
  #           source: "[^a-zA-Z0-9 -]"
  #           target: "_"
  #       - regexp:
  #           source: "(.*)"
  #           target: "minio_$1"
  #   - extract:
  #       key: Cloudflare
  #     rewrite:
  #       - regexp:
  #           source: "[^a-zA-Z0-9 -]"
  #           target: "_"
  #       - regexp:
  #           source: "(.*)"
  #           target: "cloudflare_$1"
