---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-nfs
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 1Mi
  nfs:
    path: "/mnt/tank/backups/postgres"
    server: truenas.aresu.eu
  persistentVolumeReclaimPolicy: Retain
  storageClassName: postgres-nfs
