---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mikrotik-exporter
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  values:
    controllers:
      mikrotik-exporter:
        annotations:
          reloader.stakater.com/auto: "true"

        pod:
          securityContext:
            runAsGroup: 101
            runAsUser: 100
            fsGroup: 101
            fsGroupChangePolicy: "OnRootMismatch"
            runAsNonRoot: true

        containers:
          app:
            image:
              repository: ghcr.io/akpw/mktxp
              tag: main@sha256:87e8449cd397228c78fc467bc95c57be9784e142f8b122d16baa54b36efa094e
            args:
              - --cfg-dir
              - /mktxp_config
              - export
            probes:
              liveness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /
                    port: &port 49090
                  initialDelaySeconds: 15
                  periodSeconds: 20
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness:
                enabled: false
              startup:
                enabled: false
            resources:
              requests:
                cpu: 10m
                memory: 32Mi
              limits:
                memory: 256Mi
            securityContext:
              allowPrivilegeEscalation: false
              capabilities:
                drop:
                  - "ALL"

    service:
      app:
        controller: mikrotik-exporter
        ports:
          http:
            port: *port

    serviceMonitor:
      app:
        serviceName: mikrotik-exporter
        endpoints:
          - port: http
            interval: 45s
            scrapeTimeout: 30s

    persistence:
      config:
        type: secret
        name: mikrotik-exporter-secret
        defaultMode: 0644 # Set readable permissions
        globalMounts:
          - path: /mktxp_config
