---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mikrotik-exporter
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.7.1
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  values:
    controllers:
      mikrotik-exporter:
        pod:
          securityContext:
            runAsGroup: 1000
            runAsUser: 1000
            runAsNonRoot: true

        containers:
          mikrotik-exporter:
            image:
              repository: ghcr.io/akpw/mktxp
              tag: 1.2.9@sha256:d69cd5ff47bb2a2c1194e7911805d8d1acd3e32afb3cde78620fb0b79680221f
            args:
              - --cfg-dir
              - /mktxp_config
              - export
            probes:
              liveness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /
                    port: &port 49090
                  initialDelaySeconds: 15
                  periodSeconds: 20
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness:
                enabled: false
              startup:
                enabled: false
            resources:
              requests:
                cpu: 10m
                memory: 32Mi
              limits:
                memory: 256Mi
            securityContext:
              allowPrivilegeEscalation: false
              capabilities:
                drop:
                  - "ALL"

    service:
      app:
        controller: mikrotik-exporter
        annotations:
          prometheus.io/port: "49090"
          prometheus.io/scrape: "true"
        ports:
          http:
            port: *port

    serviceMonitor:
      app:
        serviceName: mikrotik-exporter
        endpoints:
          - port: http
            interval: 5s

    persistence:
      config:
        type: secret
        name: mikrotik-exporter-secret
        globalMounts:
          - path: /mktxp_config
