---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: unifi
spec:
  chartRef:
    kind: OCIRepository
    name: unifi
  interval: 30m
  values:
    controllers:
      unifi:
        annotations:
          reloader.stakater.com/auto: "true"
        pod:
          securityContext:
            runAsUser: 999
            runAsGroup: 999
            runAsNonRoot: true
            fsGroup: 999
            fsGroupChangePolicy: "OnRootMismatch"
        containers:
          app:
            image:
              repository: ghcr.io/jacobalberty/unifi-docker
              tag: v9.5.21@sha256:e21d932b36ceca1f3cfadb021f207016659bc8f7a59cd1b0d6ecf7ecd7067383
            env:
              RUNAS_UID0: false
              UNIFI_UID: 999
              UNIFI_GID: 999
              UNIFI_STDOUT: true
              JVM_INIT_HEAP_SIZE:
              JVM_MAX_HEAP_SIZE: 512M
            resources:
              requests:
                memory: 1Gi
                cpu: 50m
    service:
      app:
        type: LoadBalancer
        annotations:
          external-dns.alpha.kubernetes.io/hostname: unifi-controller.aresu.eu
          lbipam.cilium.io/ips: ${SVC_UNIFIDIRECT_ADDR}
        ports:
          https:
            port: 443
            protocol: HTTPS
          controller:
            port: 8080
            protocol: TCP
          portal-http:
            port: 8880
            protocol: HTTP
          portal-https:
            port: 8843
            protocol: HTTPS
          speedtest:
            port: 6789
            protocol: TCP
          stun:
            port: 3478
            protocol: UDP
          syslog:
            port: 5514
            protocol: UDP
          discovery:
            port: 10001
            protocol: UDP
    persistence:
      config:
        existingClaim: unifi
        globalMounts:
          - path: /unifi
    route:
      app:
        hostnames:
          - unifi.aresu.eu
        parentRefs:
          - name: envoy-internal
            namespace: network
