apiVersion: v1
kind: PersistentVolume
metadata:
  name: "${VOLSYNC_CLAIM:-${APP}}"
spec:
  capacity:
    storage: "${VOLSYNC_CAPACITY:-1Gi}"
  volumeMode: Filesystem
  accessModes:
    - "${VOLSYNC_ACCESSMODES:-ReadWriteOnce}"
  storageClassName: longhorn
  csi:
    driver: driver.longhorn.io
    fsType: ext4
    volumeAttributes:
      numberOfReplicas: '1'
      staleReplicaTimeout: '2880'
    volumeHandle: "${VOLSYNC_CLAIM:-${APP}}"
