---
# yaml-language-server: $schema=https://k8s-schemas.bjw-s.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &appname crunchy-postgres-operator
  namespace: &namespace database
spec:
  targetNamespace: *namespace
  commonMetadata:
    labels:
      app.kubernetes.io/name: *appname
  interval: 1h
  timeout: 5m
  path: ./kubernetes/apps/database/crunchy-postgres-operator/operator
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  wait: true
  dependsOn:
    - name: onepassword-store
      namespace: external-secrets
# ---
# # yaml-language-server: $schema=https://k8s-schemas.bjw-s.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
# apiVersion: kustomize.toolkit.fluxcd.io/v1
# kind: Kustomization
# metadata:
#   name: &appname crunchy-postgres-operator-cluster
#   namespace: &namespace database
# spec:
#   targetNamespace: *namespace
#   commonMetadata:
#     labels:
#       app.kubernetes.io/name: *appname
#   interval: 1h
#   timeout: 5m
#   path: ./kubernetes/apps/database/crunchy-postgres-operator/cluster
#   prune: true
#   sourceRef:
#     kind: GitRepository
#     name: flux-system
#     namespace: flux-system
#   wait: true
#   # postBuild:
#   #   substituteFrom:
#   #     - kind: Secret
#   #       name: crunchy-postgres-r2
#   #       optional: false
#   dependsOn:
#     - name: crunchy-postgres-operator
#       namespace: database
#     - name: onepassword-store
#       namespace: external-secrets
# ---
# # yaml-language-server: $schema=https://k8s-schemas.bjw-s.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
# apiVersion: kustomize.toolkit.fluxcd.io/v1
# kind: Kustomization
# metadata:
#   name: &appname crunchy-postgres-operator-secretstore
#   namespace: &namespace database
# spec:
#   targetNamespace: *namespace
#   commonMetadata:
#     labels:
#       app.kubernetes.io/name: *appname
#   interval: 1h
#   timeout: 5m
#   path: ./kubernetes/apps/database/crunchy-postgres-operator/clustersecretstore
#   prune: true
#   sourceRef:
#     kind: GitRepository
#     name: flux-system
#     namespace: flux-system
#   wait: true
#   dependsOn:
#     - name: crunchy-postgres-operator-cluster
#       namespace: database
#     - name: external-secrets
#       namespace: external-secrets
# ---
# # yaml-language-server: $schema=https://k8s-schemas.bjw-s.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
# apiVersion: kustomize.toolkit.fluxcd.io/v1
# kind: Kustomization
# metadata:
#   name: &appname crunchy-postgres-userinit-controller
#   namespace: &namespace database
# spec:
#   targetNamespace: *namespace
#   commonMetadata:
#     labels:
#       app.kubernetes.io/name: *appname
#   interval: 1h
#   timeout: 5m
#   path: ./kubernetes/apps/database/crunchy-postgres-operator/userinit-controller
#   prune: true
#   sourceRef:
#     kind: GitRepository
#     name: flux-system
#     namespace: flux-system
#   wait: false
