---
networks:
  proxy:
    name: proxy
    external: true
services:
  forgejo:
    container_name: forgejo
    environment:
      - USER_UID=568
      - USER_GID=568
    image: codeberg.org/forgejo/forgejo:15
    labels:
      - traefik.enable=true
      - traefik.http.routers.forgejo.rule=Host(`git.aresu.eu`)
      - traefik.http.services.forgejo.loadbalancer.server.port=3000
    networks:
      - proxy
    ports:
      - 222:22
    restart: unless-stopped
    volumes:
      - /mnt/fast/apps/forgejo:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
