---
networks:
  proxy:
    name: proxy
    external: true
services:
  forgejo:
    container_name: forgejo
    environment:
      - USER_UID=568
      - USER_GID=568
      - FORGEJO__cron__archive_cleanup__ENABLED=true
      - FORGEJO__cron__archive_cleanup__OLDER_THAN=2h
      - FORGEJO__cron__archive_cleanup__RUN_AT_START=true
      - FORGEJO__cron__archive_cleanup__SCHEDULE="@every 1h"
      - FORGEJO__mailer__ENABLED=false
      - FORGEJO__openid__ENABLE_OPENID_SIGNIN=false
      - FORGEJO__openid__ENABLE_OPENID_SIGNUP=false
      - FORGEJO__repository__DEFAULT_REPO_UNITS=repo.code,repo.releases,repo.issues,repo.pulls,repo.actions
      - FORGEJO__repository__DISABLED_REPO_UNITS=repo.ext_wiki,repo.ext_issues
      - FORGEJO__repository__pull-request__DEFAULT_MERGE_STYLE=squash
      - FORGEJO__service__ALLOW_ONLY_EXTERNAL_REGISTRATION=true
      - FORGEJO__service__DEFAULT_ENABLE_TIMETRACKING=false
      - FORGEJO__service__ENABLE_INTERNAL_SIGNIN=false
      - FORGEJO__service__ENABLE_PASSWORD_SIGNIN_FORM=false
      - FORGEJO__service__explore__DISABLE_CODE_PAGE=false
      - FORGEJO__service__explore__DISABLE_ORGANIZATIONS_PAGE=true
      - FORGEJO__service__explore__DISABLE_USERS_PAGE=true
      - FORGEJO__service__explore__REQUIRE_SIGNIN_VIEW=false
      - FORGEJO__service__SHOW_REGISTRATION_BUTTON=false
      - FORGEJO__webhook__ALLOWED_HOST_LIST=*
    image: codeberg.org/forgejo/forgejo:16
    labels:
      - traefik.enable=true
      - traefik.http.routers.forgejo.rule=Host(`git.aresu.eu`)
      - traefik.http.services.forgejo.loadbalancer.server.port=3000
    networks:
      - proxy
    ports:
      - 222:22
      - 3000:3000
    restart: unless-stopped
    volumes:
      - /mnt/fast/apps/forgejo:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
