---
apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: homeassistant
  labels:
    kubernetes.io/service-name: homeassistant
addressType: IPv4
endpoints:
  - addresses:
      - 10.17.1.4
ports:
  - name: http
    appProtocol: http
    protocol: TCP
    port: 8123
