---
# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"

vars:
  # Define your MikroTik device IPs here
  DEVICES: ["10.17.1.1", "10.17.1.68", "10.17.1.69"]
  TRAVEL_ROUTER: 10.17.4.1

tasks:
  upgrade-all:
    desc: Upgrade all MikroTik devices in the home network
    cmds:
      - for:
          var: DEVICES
        task: _upgrade-device
        vars:
          HOST: "{{ .ITEM }}"

  upgrade-travel:
    desc: Upgrade travel router
    cmds:
      - task: _upgrade-device
        vars:
          HOST: "{{ .TRAVEL_ROUTER }}"

  _upgrade-device:
    desc: Fully upgrade a MikroTik device
    internal: true
    vars:
      HOST: "{{ .HOST }}"
    cmds:
      - task: _upgrade-packages
        vars:
          HOST: "{{ .HOST }}"
      - until nc -z {{.HOST}} 22; do sleep 5; done
      - task: _upgrade-firmware
        vars:
          HOST: "{{ .HOST }}"
      - until nc -z {{.HOST}} 22; do sleep 5; done
      - task: _upgrade-modem
        vars:
          HOST: "{{ .HOST }}"

  _upgrade-packages:
    desc: Update packages on a device
    internal: true
    vars:
      HOST: "{{ .HOST }}"
    status:
      - ssh {{.HOST}} "/system/package/update/check-for-updates" | grep -c "up to date"
    cmds:
      - ssh {{.HOST}} "/system/package/update/install"

  _upgrade-firmware:
    desc: Update firmware on a MikroTik device
    internal: true
    vars:
      HOST: "{{ .HOST }}"
    status:
      - ssh {{.HOST}} ":put ([/system/routerboard/get current-firmware]=[/system/routerboard/get upgrade-firmware])" | grep -q "true"
    cmds:
      - ssh {{.HOST}} "/system/routerboard/upgrade"
      - cmd: ssh {{.HOST}} "/system/reboot"
        ignore_error: true

  _upgrade-modem:
    desc: Update modem firmware on a MikroTik device, if present
    internal: true
    vars:
      HOST: "{{ .HOST }}"
    status:
      - ssh {{.HOST}} "/interface/lte/print count-only" | grep -qE "(error|0)"
    cmds:
      - ssh {{.HOST}} ":foreach i in [/interface/lte/find] do={[/interface/lte/firmware-upgrade \$i]}"
      # - ssh {{.HOST}} "for i from=([/interface/lte/print count-only as-value] - 1) to=0 do={[/interface/lte/firmware-upgrade \$i]}"
