---
apiVersion: longhorn.io/v1beta2
kind: RecurringJob
metadata:
  name: snapshot-cleanup
spec:
  concurrency: 1
  cron: "0 2 * * *"
  name: snapshot-cleanup
  groups:
    - default
  task: snapshot-cleanup
