---
# yaml-language-server: $schema=https://k8s-schemas.bjw-s.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &appname intel-device-plugins-operator
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *appname
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: *appname
      namespace: system
  interval: 1h
  path: "./kubernetes/apps/system/intel-device-plugins/operator"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  timeout: 5m
  wait: false
---
# yaml-language-server: $schema=https://k8s-schemas.bjw-s.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &appname intel-device-plugins-gpu
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *appname
  dependsOn:
    - name: intel-device-plugins-operator
    - name: node-feature-discovery
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: *appname
      namespace: system
  interval: 1h
  path: "./kubernetes/apps/system/intel-device-plugins/gpu"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  timeout: 5m
  wait: false
# ---
# # yaml-language-server: $schema=https://k8s-schemas.bjw-s.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
# apiVersion: kustomize.toolkit.fluxcd.io/v1
# kind: Kustomization
# metadata:
#   name: &appname intel-device-plugins-xpumanager
# spec:
#   commonMetadata:
#     labels:
#       app.kubernetes.io/name: *appname
#   interval: 1h
#   path: "./kubernetes/apps/system/intel-device-plugins/xpumanager"
#   sourceRef:
#     kind: GitRepository
#     name: flux-system
#     namespace: flux-system
#   timeout: 5m
#   prune: true
#   wait: false
