---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: longhorn
resources:
  - ./longhorn/ks.yaml
components:
  - ../../components/namespace
  - ../../components/flux/cluster-settings
