---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: longhorn
components:
  - ../../components/cluster-settings
  - ../../components/flux-alerts
resources:
  - ./namespace.yaml
  - ./longhorn/ks.yaml
