---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: open-thread-border-router
spec:
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  interval: 30m
  dependsOn:
    - name: longhorn
      namespace: longhorn
  values:
    controllers:
      otbr:
        pod:
          securityContext:
            runAsUser: 2000
            runAsGroup: 2000
            fsGroup: 2000
            fsGroupChangePolicy: "OnRootMismatch"

        containers:
          app:
            image:
              repository: openthread/border-router
              tag: latest@sha256:d40a06f3e3cf42ab4ec0eb2e7016774b34d0e3cc2e97ada859de098c79c931cf
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /
                    port: 80
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes
              startup:
                enabled: true
                spec:
                  failureThreshold: 30
                  periodSeconds: 10
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                add:
                  - NET_ADMIN
            resources:
              requests:
                cpu: 100m
              limits:
                squat.ai/thread: 1
                memory: 100Mi

    service:
      app:
        controller: otbr
        type: LoadBalancer
        ports:
          http:
            port: &port 80

    ingress:
      app:
        annotations:
          nginx.ingress.kubernetes.io/backend-protocol: HTTPS
        className: internal-nginx
        hosts:
          - host: "otbr.aresu.eu"
            paths:
              - path: /
                service:
                  identifier: app
                  port: http

    persistence:
      config:
        existingClaim: otbr-data
        advancedMounts:
          otbr:
            app:
              - path: /data

    route:
      app:
        hostnames:
          - otbr.aresu.eu
        parentRefs:
          - name: internal
            namespace: kube-system
            sectionName: https
        rules:
          - backendRefs:
              - name: otbr
                port: *port
