---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: open-thread-border-router
spec:
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  interval: 30m
  dependsOn:
    - name: longhorn
      namespace: longhorn
  values:
    controllers:
      otbr:
        containers:
          app:
            image:
              repository: openthread/otbr
              tag: latest #@sha256:d40a06f3e3cf42ab4ec0eb2e7016774b34d0e3cc2e97ada859de098c79c931cf
            args:
              - --radio-url
              - spinel+hdlc+uart:///dev/ttyACM0?uart-baudrate=115200
              - --backbone-interface
              - enp2s0
              - --usage
            env:
              HTTP_PORT: 8888
              OT_THREAD_IF: wpan0
              # OT_RCP_DEVICE: spinel+hdlc+uart:///dev/serial/by-id/usb-Nordic_Semiconductor_nRF528xx_OpenThread_Device_*
            probes:
              liveness: &probes
                enabled: false
                custom: true
                spec:
                  exec:
                    command:
                    - ot-ctl
                    - state
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes
              startup:
                enabled: false
                spec:
                  failureThreshold: 30
                  periodSeconds: 10
            securityContext:
              privileged: true
              runAsGroup: 0
              runAsNonRoot: false
              runAsUser: 0
              capabilities:
                add:
                  - NET_ADMIN
                  - NET_RAW
                  - SYS_ADMIN
              sysctls:
              - name: net.ipv4.ip_forward
                value: "1"
              - name: net.ipv6.conf.all.forwarding
                value: "1"
            resources:
              # requests:
                # cpu: 100m
              limits:
                squat.ai/thread: 1
                # memory: 100Mi

    defaultPodOptions:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet

    service:
      app:
        controller: otbr
        type: LoadBalancer
        ports:
          http:
            port: &port 8888

    ingress:
      app:
        enabled: true
        className: "internal-nginx"
        hosts:
          - host: otbr.aresu.eu
            paths:
              - path: /
                service:
                  identifier: app
                  port: http

    persistence:
      config:
        existingClaim: otbr-data
        advancedMounts:
          otbr:
            app:
              - path: /data
      thread:
        type: hostPath
        hostPath: /dev/serial/by-id
      tun:
        type: hostPath
        hostPath: /dev/net/tun
