---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: downloads
resources:
  # Flux-Kustomizations
  - ./bazarr/ks.yaml
  - ./flaresolverr/ks.yaml
  - ./lidarr/ks.yaml
  - ./prowlarr/ks.yaml
  - ./qbittorrent/ks.yaml
  - ./radarr/ks.yaml
  - ./readarr/ks.yaml
  - ./sonarr/ks.yaml
components:
  - ../../components/namespace
  - ../../components/flux/alerts
  - ../../components/flux/cluster-settings
