---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: downloads
components:
  - ../../components/cluster-settings
  - ../../components/flux-alerts
resources:
  - ./namespace.yaml
  # Flux-Kustomizations
  - ./bazarr/ks.yaml
  - ./flaresolverr/ks.yaml
  - ./lidarr/ks.yaml
  - ./prowlarr/ks.yaml
  - ./qbittorrent/ks.yaml
  - ./radarr/ks.yaml
  - ./readarr/ks.yaml
  - ./sonarr/ks.yaml
  - ./tqm/ks.yaml
