---
# yaml-language-server: $schema=https://k8s-schemas.bjw-s.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: esphome-secrets
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: esphome-secrets
    creationPolicy: Owner
    template:
      data:
        secrets.yaml: |-
          wifi_ssid_upstairs: "{{ .esphome_wifi_ssid }}"
          wifi_ssid_downstairs: "{{ .esphome_wifi_ssid }}"
          wifi_password: "{{ .esphome_wifi_password }}"

          fallback_password: "{{ .esphome_wifi_fallback_ssid_password }}"
          iot_domain: "{{ .esphome_domain }}"
          api_key: "{{ .esphome_api_key }}"
          ota_password: "{{ .esphome_ota_password }}"

          mqtt_host: mqtt.aresu.eu
          mqtt_user: "{{ .mqtt_user_mqtt_username }}"
          mqtt_pwd: "{{ .mqtt_user_mqtt_password }}"

          webserver_username: "{{ .esphome_webserver_username }}"
          webserver_password: "{{ .esphome_webserver_password }}"
  dataFrom:
    - extract:
        key: esphome
      rewrite:
        - regexp:
            source: "(.*)"
            target: "esphome_$1"
    - extract:
        key: MQTT
      rewrite:
        - regexp:
            source: "(.*)"
            target: "mqtt_$1"
---
# yaml-language-server: $schema=https://k8s-schemas.bjw-s.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: esphome-deploykey
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: esphome-deploykey
    creationPolicy: Owner
  data:
    - secretKey: id_ed25519
      remoteRef:
        key: esphome
        property: github_deploy_key
