---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: demo
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system

  values:
    controllers:
      demo:
        annotations:
          reloader.stakater.com/auto: "true"

        containers:
          app:
            image:
              repository: nginx
              tag: 1.27.4
            env:
              HTTP_PORT: &port 80
              LOG_WITHOUT_NEWLINE: "true"
              LOG_IGNORE_PATH: "/healthz"
            resources:
              requests:
                cpu: 5m
                memory: 64Mi
              limits:
                memory: 64Mi

    service:
      app:
        controller: demo
        ports:
          http:
            port: *port

    ingress:
      app:
        className: external-nginx
        hosts:
          - host: "demo.aresu.eu"
            paths:
              - path: /
                service:
                  identifier: app
                  port: http

    persistence:
      config-file:
        type: configMap
        name: demo-configmap
        globalMounts:
          - path: /usr/share/nginx/html
            readOnly: true
