# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
  namespace: flux-system
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:f5QQ+QIARM8=,iv:i0TI1sEbjA3te8gMgaOeORWKuXT7YzPhDQjjPuw7pws=,tag:EmRTUTc9LqzI6s5oMKr9lg==,type:str]
  SECRET_ACME_EMAIL: ENC[AES256_GCM,data:YYbKQ1Ugtxv74t4oJ6xAU7xKNaeqkg==,iv:Hh6OpRmFfnFAC6vLARwXYwym/ptVcPcZPsyTl6VePx0=,tag:SlpoM0NJ+C2cCAdsGdtjRQ==,type:str]
  SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:cVJ9+YzP4cEfBN26zD4OXBg85Aw469KMOG2kAD5XLROF7m09,iv:B6gWPnAhCDd+I99Q2X/GG7A/OXrhyZ0c8cQQaH0P1+w=,tag:6TR2DhmGCZiezbg+GSqdTA==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age19ufzusf8ls394p4kl5498myl24w7x6ggc5w9grq4tk8dcyh709ls6ku97r
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHU1R2UzNsTXBuN0JydENI
        M082cFNoR0pqNE9hbGx2d1FvNlZpeHpPTmdjCjlvd3A0Qi82clEyZ0pqa1BWdTkx
        Y0txdlJpMHBRQ05HOVVIL2tZNFhFemsKLS0tIGVhMHBHclU5U3I5eTBzOHZDRml3
        OXFLb0cxbzlnUVpaTC9XU054dlNaV1kKE30gKsajkLhJduWM2hmWxIZeUq2TrfmZ
        OvhQGwR2DKP9rpQasY9XgJx1EY0uohTsjzh1NH2OiKoLeXHliGJoFw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-01-26T15:06:31Z"
  mac: ENC[AES256_GCM,data:VIbdBaTS7Lpjsvuk8hfqjL06BV+SS2MML2GHQyuZfkYhwU5hJ2XeT/iS7qqvEf8hIBiHK0Gq7VwsGjKsnECPKBIMfz7rwL5oiMS5BLYx0Rp80jSFE/qSoriKX14dlb7p9rUtHymkBZ4QjWBdfPjcayTbGE0kKhfUugsuHqVWRTE=,iv:L9euRr32Mg5L3I6Bg+4lEbR2w76MFVWSbAkWeUaeiKM=,tag:TM8RH5WaVUywdHkHO367ZQ==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
