---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-primary-v1
  annotations:
    helm.sh/resource-policy: "keep"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: longhorn-replicated
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-backups-v1
  annotations:
    helm.sh/resource-policy: "keep"
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Gi
  storageClassName: ""
  volumeName: mongodb-backups-v1
