services:
  app:
    container_name: doco-cd-updater
    image: ghcr.io/kimdre/doco-cd:0.97.0@sha256:2fbcb0ecf0c9041e0386852aaeffc3b4a98faef870171105f9c9a2db52e00ecb
    restart: unless-stopped
    environment:
      TZ: Europe/Rome
      HTTP_PORT: 8000
      DEPLOY_CONFIG_BASE_DIR: /docker/truenas
      # GIT_ACCESS_TOKEN: ${GIT_ACCESS_TOKEN}
      POLL_CONFIG: |
        - url: https://github.com/GiorgioAresu/home-ops.git
          reference: main
          interval: 300
          target: updater  # deploys the updater target on change
      SCHEDULER_ENABLED: false  # disable scheduler on updater instance
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - updater-data:/data

volumes:
  updater-data: