apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:l7XIjJ6YJ3UIW/m1X6p4efwA6X90RlzVtlEzggj4yCxLOAPVjD7Imw==,iv:m7GIUO/cVfk8FTEHp3E+2mne3gTgaKon6asjxb+5AKw=,tag:n4qkRof4OXe+mNLaFAT6lw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19ufzusf8ls394p4kl5498myl24w7x6ggc5w9grq4tk8dcyh709ls6ku97r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMZ1M5TWFoaHBKYU91YkUv
            WUtkZmtEZ1AybEFnc0FPaWJqeHdjbDNOSkU4Ci9yNXY2c0ZEa1U2c2hJQjF6bzRK
            VkFXTFR2UWpXem54bWMxOWFETmEzdVEKLS0tIDZ6aDNZRVFNTUdITjZyNWYyaFZX
            THV4VnF2N0FQOThibllOS0Z0NjRBc1UKAZk1AizIWEyRewIRV1/iDuxcvy+P4is2
            zE7xW1oUSLcwHF9xTLb1f0iA6fkdVyp2KGJi73s0S7pfJ4+9OyWbng==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-04-14T22:37:52Z"
    mac: ENC[AES256_GCM,data:vvJDK6ARFViTPq9Ekr3dVIYF+/eOlerrgSS5y2R+UuHRMYEATGuDv3rlfkj14dMjiQ4gqyJ5sCBmamAXL5fPRJzcTwTYja7ogrZjiEq8aP+lpHOBHC+ho3extqasarKwAOUHTOLb1at7YMJvHUEvUl+ANSuIIYSNbn63RSzLCmg=,iv:oB7Kn2xbGfK0OJBA2QqZHvPwL6SYB/aeMMu7eLr0yWQ=,tag:XHEVojeu91zZrp9jdR4YQw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
