apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:HuQs3v3q7gYFUvFKVV2jXY1O9p5th+jNfA7nMprP5rNRi18DDNv2zQ==,iv:WHto+sS/js8OhawseEh5D5EyiOKEsK5FJKrSq6co91M=,tag:fOMr5H9ur1vtsOTBWfVG1A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19ufzusf8ls394p4kl5498myl24w7x6ggc5w9grq4tk8dcyh709ls6ku97r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHMDZYRnlqNHpIdXJGS2h0
            Sk1mQ1lrV1ZNV0lVTGYrOUdjRW1YNmMwYUE4ClRZV1hYZ1N5UmZBT3dpcHFYV0pN
            Y2VCb1pBU2crcm0vdTM4dlNjT0dNa1EKLS0tIGpqTXNaUDNZaFJuVGtJSUNzQjVw
            WnJvR2FjT2RRZzFzanhZM2FmUXA2VDQKyzF5ZN9oKbwavp7Z58m6gK5/k5b95KD3
            nxFknxFxDEPimqMWzi5gjihKINE6m4d91dB98CL/Fs/QMIoueRKM0w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-04-14T22:27:34Z"
    mac: ENC[AES256_GCM,data:dOnj+oEg9JiG60lt/p8q6K/Gx9H3ANV4U6X30r3cFWMZotXI15S4l2LWpKDwKUCB/N6FNZ1Mlkmxs6f3RkUe7+zSOLdt5HyL2WkXo/R3UHFX4QeuknbFWl2btAHVMdAADthonb0w7z9rWb8LirOVWmUFORNGZ1l12CEobjkyZeg=,iv:vCWbh8GZgjN9Pxmz2627DXfOkygcgUqpyC24KmKk8Vo=,tag:0rVZiY12u0AuYBQ3bjoRsQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
