apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:DJSNy1uZJErAlELMPA3TVm+LHA083RUyItda/5P/5joxDZaqA2V30g==,iv:BraFEBpbdRuKuRQgAB+ZexstEpdtu7n9ttdDR06xYnM=,tag:3Ye/bY8mWfSgy3Y2RVdrSw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19ufzusf8ls394p4kl5498myl24w7x6ggc5w9grq4tk8dcyh709ls6ku97r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArWTg3SllNOGtlNHNlZzVo
            dHNOOGxHTjJsUFlrajhxRjZhZEhWVVlLb0ZBCnQ0ZDRkUGMzNFFEelRUUzNDNGl4
            NHl6eHE0Q3lSck50czlqTFpLbm9jSTgKLS0tIHVMbDRoSWlva0ZINk1iZ2tsN1dl
            OEw5ZlNLNGtNZnp5N3B3RWpwSzlDV2MK+qnuzt8rjN+Gqo3WbtORVajriKrAK9Hm
            SCeCpt640xWo5hLbHRZuZXPGm9e57F+gtDg1mgZTZdlM3P4C4Tlg+Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-04-14T10:21:12Z"
    mac: ENC[AES256_GCM,data:opZa2TXtYrOiVmvLFj1gk/A9SZE/MLSPHGzHJ1j+ebBT85ht0uVmqo+yzwLdH67vvIBxlLCYrUibtIo4y/+9DgiSRmBJdlkm3CaSRibO0dziXkvkwGOI424RkpFs2bwCknisEw55Sbn+7c3Sk7mQFbZ2cARRZZFGGCY9GkzIXmA=,iv:8Ss4amn7o/t5/I8pVYkqIC/rqfyrGcVmyHpOtJjHdkg=,tag:qizGS3n3t2pXuw3ei914gw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
