---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: readarr
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.1.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    controllers:
      readarr:
        annotations:
          reloader.stakater.com/auto: "true"
        # initContainers:
        #   init-db:
        #     image:
        #       repository: ghcr.io/onedr0p/postgres-init
        #       tag: 16
        #     envFrom: &envFrom
        #       - secretRef:
        #           name: readarr-secret
        containers:
          app:
            image:
              repository: ghcr.io/onedr0p/readarr-develop
              tag: 0.3.22.2499@sha256:54883dc20b860ca5bc53f710745ec6dd31437de293d7f68284a0ea48cd494a38
            env:
              TZ: ${TIMEZONE}
              PUID: 568
              PGID: 1003
            # envFrom: *envFrom
            probes:
              liveness: &probes
                enabled: true
                spec:
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 1Gi
    service:
      app:
        controller: readarr
        ports:
          http:
            port: 8787
    ingress:
      app:
        className: internal
        annotations:
          hajimari.io/enable: "true"
          hajimari.io/group: "media"
          hajimari.io/icon: "bookshelf"
          hajimari.io/info: "Books"
        hosts:
          - host: "{{ .Release.Name }}.${SECRET_DOMAIN}"
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
    persistence:
      # config:
      #   enabled: true
      #   type: persistentVolumeClaim
      #   existingClaim: readarr-config-v1
      #   globalMounts:
      #     - path: /config
      config:
        type: emptyDir
      tmp:
        type: emptyDir
      books:
        type: nfs
        server: "${TRUENAS_ADDR}"
        path: /mnt/tank/media
        globalMounts:
          - path: /books
            subPath: Books
      downloads:
        type: nfs
        server: "${TRUENAS_ADDR}"
        path: /mnt/tank/downloads
        globalMounts:
          - path: /downloads
            subPath: complete/books
