---
apiVersion: kaniop.rs/v1beta1
kind: KanidmOAuth2Client
metadata:
  name: forgejo
spec:
  kanidmRef:
    name: kanidm
    namespace: security
  displayname: Forgejo
  origin: https://git.aresu.eu/
  redirectUrl:
    - https://git.aresu.eu/user/oauth2/kanidm/callback
  scopeMap:
    - group: forgejo_admins@idm.aresu.eu
      scopes:
        - openid
        - profile
        - email
        - groups
    - group: forgejo_users@idm.aresu.eu
      scopes:
        - openid
        - profile
        - email
        - groups
  strictRedirectUrl: true
  preferShortUsername: true
  secretKeyAliases:
    clientId:
      - key
    clientSecret:
      - secret
  disableConsentPrompt: true
