---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
resources:
  - ./demo/ks.yaml
  - ./frigate/ks.yaml
  - ./vlmcsd/ks.yaml
components:
  - ../../components/namespace
  - ../../components/flux/alerts
  - ../../components/flux/cluster-settings
