---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/volsync.backube/replicationsource_v1alpha1.json
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: ${APP}
spec:
  sourcePVC: "${VOLSYNC_CLAIM:-${APP}}"
  trigger:
    schedule: "0 * * * *"
  restic:
    accessModes:
      - "${VOLSYNC_SNAP_ACCESSMODES:-ReadWriteOnce}"
    cacheAccessModes:
      - "${VOLSYNC_CACHE_ACCESSMODES:-ReadWriteOnce}"
    cacheCapacity: "${VOLSYNC_CACHE_CAPACITY:-1Gi}"
    cacheStorageClassName: "${VOLSYNC_CACHE_SNAPSHOTCLASS:-longhorn-singlereplica}"
    copyMethod: "${VOLSYNC_COPYMETHOD:-Snapshot}"
    moverSecurityContext:
      runAsUser: ${APP_UID:-2000}
      runAsGroup: ${APP_GID:-2000}
      fsGroup: ${APP_GID:-2000}
    pruneIntervalDays: 7
    repository: ${APP}-volsync-nfs
    retain:
      hourly: 24
      daily: 7
      monthly: 6
    storageClassName: "${VOLSYNC_STORAGECLASS:-longhorn-singlereplica}"
    volumeSnapshotClassName: "${VOLSYNC_SNAPSHOTCLASS:-longhorn-snapshotclass}"
