---
working_dir: ./docker/truenas
auto_discover: true
auto_discover_opts:
  depth: 1
  delete: true
external_secrets:
  EMAIL: op://Services/LetsEncrypt/username
  GARAGE_ADMIN_TOKEN: op://Services/Garage/GARAGE_ADMIN_TOKEN
  GARAGE_METRICS_TOKEN: op://Services/Garage/GARAGE_METRICS_TOKEN
  GARAGE_RPC_SECRET: op://Services/Garage/GARAGE_RPC_SECRET
  TRAEFIK_API_BASICAUTH_DASHBOARD: op://Services/Traefik/htpassword
  TRAEFIK_CF_DNS_API_TOKEN: op://Automation/Cloudflare/API Tokens/truenas_traefik
