---
# yaml-language-server: $schema=https://k8s-schemas.bjw-s.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: longhorn
spec:
  interval: 30m
  chart:
    spec:
      chart: longhorn
      version: 1.10.0
      sourceRef:
        kind: HelmRepository
        name: longhorn
      interval: 30m
  values:
    # csi:
    #   attacherReplicaCount: 1 # TODO: Increase this to 2-3 when adding nodes
    #   provisionerReplicaCount: 1 # TODO: Increase this to 2-3 when adding nodes
    #   resizerReplicaCount: 1 # TODO: Increase this to 2-3 when adding nodes
    #   snapshotterReplicaCount: 1 # TODO: Increase this to 2-3 when adding nodes

    defaultSettings:
      autoCleanupSnapshotAfterOnDemandBackupCompleted: true
      autoCleanupSnapshotWhenDeleteBackup: true
      concurrentAutomaticEngineUpgradePerNodeLimit: "1"
      concurrentReplicaRebuildPerNodeLimit: "3"
      concurrentVolumeBackupRestorePerNodeLimit: "3"
      createDefaultDiskLabeledNodes: true
      defaultDataLocality: best-effort
      defaultDataPath: /var/mnt/longhorn
      defaultLonghornStaticStorageClass: longhorn
      defaultReplicaCount: "2" # TODO: Increase this to 2-3 when adding nodes
      detachManuallyAttachedVolumesWhenCordoned: true
      #guaranteedEngineManagerCPU: 20
      #guaranteedReplicaManagerCPU: 20
      node-drain-policy: allow-if-replica-is-stopped
      #nodeDownPodDeletionPolicy: delete-both-statefulset-and-deployment-pod
      offlineRelicaRebuilding: true
      orphanAutoDeletion: true
      replicaAutoBalance: best-effort
      restoreVolumeRecurringJobs: true # Don´t need this if we create a default one and then use localpath for the ones we don´t want to backup
      # snapshotMaxCount: 10
      storageReservedPercentageForDefaultDisk: "0"
      storageMinimalAvailablePercentage: "5"
      storageOverProvisioningPercentage: "150"

    defaultBackupStore:
      backupTarget: nfs://${TRUENAS_ADDR}:/mnt/tank/longhorn-backups

    longhornUI:
      replicas: 1

    annotations:
      configmap.reloader.stakater.com/reload: longhorn-default-setting

    # TODO: Add internal separate route to replace this
    # ingress:
    #   enabled: true
    #   ingressClassName: internal-nginx
    #   annotations:
    #     hajimari.io/appName: "longhorn"
    #     hajimari.io/enable: "true"
    #     hajimari.io/group: "admin"
    #     hajimari.io/icon: "harddisk"
    #     nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    #     nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
    #     # prevent the controller from redirecting (308) to HTTPS
    #     nginx.ingress.kubernetes.io/ssl-redirect: 'false'
    #     # custom max body size for file uploading like backing image uploading
    #     nginx.ingress.kubernetes.io/proxy-body-size: 10000m
    #   host: "longhorn.${SECRET_DOMAIN}"
    #   path: /
    #   tls: true

    persistence:
      defaultClassReplicaCount: 2
      reclaimPolicy: Delete
      backupTargetName: default

    metrics:
      serviceMonitor:
        enabled: true
