---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: atuin
spec:
  chartRef:
    kind: OCIRepository
    name: atuin
  interval: 30m
  dependsOn:
    - name: longhorn
      namespace: longhorn
  values:
    controllers:
      atuin:
        annotations:
          reloader.stakater.com/auto: "true"
        pod:
          securityContext:
            runAsNonRoot: true
            runAsUser: 2000
            runAsGroup: 2000
            fsGroup: 2000
            fsGroupChangePolicy: OnRootMismatch
        containers:
          app:
            image:
              repository: ghcr.io/atuinsh/atuin
              tag: v18.9.0
            command:
              - atuin
            args:
              - server
              - start
            env:
              ATUIN_DB_URI: sqlite:///config/atuin.db
              ATUIN_HOST: 0.0.0.0
              ATUIN_PORT: &port 8888
              # ATUIN_OPEN_REGISTRATION: true
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /
                    port: *port
                  initialDelaySeconds: 10
                  periodSeconds: 10
                  timeoutSeconds: 5
                  failureThreshold: 3
              readiness: *probes
            resources:
              requests:
                cpu: 10m
                memory: 128Mi
              limits:
                memory: 256Mi
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop:
                  - ALL
    service:
      app:
        ports:
          http:
            port: *port
    persistence:
      config:
        existingClaim: atuin
    route:
      app:
        hostnames:
          - atuin.aresu.eu
        parentRefs:
          - name: envoy-internal
            namespace: network
            sectionName: https
