---
services:
  wireguard:
    cap_add:
      - NET_ADMIN
      # - SYS_MODULE #optional
    container_name: wireguard
    environment:
      - PUID=568
      - PGID=568
      - TZ=Etc/Rome
    image: lscr.io/linuxserver/wireguard:latest
    ports:
      - 51820:51820/udp
    restart: unless-stopped
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    volumes:
      - /home/truenas_admin/.config/wireguard:/config
      # - /lib/modules:/lib/modules #optional