---
receivers:
  - name: "null"
  - name: "discord"
    discord_configs:
      - webhook_url_file: /etc/secrets/discord_webhook_url
        username: AlertManager
        title: |-
          [{{ .Status | toUpper }}{{ if eq .Status "firing" }}:{{ .Alerts.Firing | len }}{{ end }}] {{ .CommonLabels.alertname }}
        message: |-
          {{- range .Alerts }}
          {{- if ne .Labels.severity "" }}
          **Severity:** _{{ .Labels.severity }}_

          {{- else }}
          **Severity:** _N/A_

          {{- end }}
          {{- if ne .Annotations.description "" }}
          **Description:** _{{ .Annotations.description }}_

          {{- else if ne .Annotations.summary "" }}
          **Summary:** _{{ .Annotations.summary }}_

          {{- else if ne .Annotations.message "" }}
          **Message:** _{{ .Annotations.message }}_

          {{- else }}
          **Description:** _N/A_

          {{- end }}
          {{- if gt (len .Labels.SortedPairs) 0 }}
          **Details:**

          {{- range .Labels.SortedPairs }}
          * **{{ .Name }}:** _{{ .Value }}_

          {{- end }}
          {{- end }}
          {{- end }}

route:
  group_by: ["alertname", "job"]
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 6h
  receiver: "discord"
  routes:
    - receiver: "null"
      matchers:
        - alertname =~ "InfoInhibitor|Watchdog"
    - receiver: "discord"
      matchers:
        - severity = critical
      continue: true

inhibit_rules:
  - source_matchers:
      - severity = "critical"
    target_matchers:
      - severity = "warning"
    equal: ["alertname", "namespace"]
