---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: plex-auto-languages
spec:
  chartRef:
    kind: OCIRepository
    name: plex-auto-languages
  interval: 30m
  dependsOn:
    - name: longhorn
      namespace: longhorn
    - name: plex
      namespace: media
  values:
    controllers:
      plex-auto-languages:
        pod:
          securityContext:
            runAsUser: 2000
            runAsGroup: 2000
            fsGroup: 2000
            fsGroupChangePolicy: "OnRootMismatch"
        containers:
          app:
            image:
              repository: remirigal/plex-auto-languages
              tag: v1.2.3@sha256:54bd9cf5d399514b8ed3052ce1d01a14375825a429653cb06da129685740889e
            env:
              PLEX_URL: http://plex.media.svc.cluster.local:32400
              PLEX_TOKEN:
                valueFrom:
                  secretKeyRef:
                    name: plex-image-cleanup-secret
                    key: PLEX_TOKEN
            resources:
              requests:
                cpu: 5m
              limits:
                memory: 192Mi
    persistence:
      config:
        existingClaim: plex-auto-languages-config
        globalMounts:
          - path: /config
