---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: observability
resources:
  - ./blackbox-exporter/ks.yaml
  - ./fluent-bit/ks.yaml
  - ./grafana/ks.yaml
  - ./kube-state-metrics/ks.yaml
  - ./kube-prometheus-stack/ks.yaml
  - ./loki/ks.yaml
  - ./mikrotik-exporter/ks.yaml
  - ./node-exporter/ks.yaml
  - ./silence-operator/ks.yaml
  - ./smartctl-exporter/ks.yaml
components:
  - ../../components/namespace
  - ../../components/flux/cluster-settings
