apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_EXAMPLE: ENC[AES256_GCM,data:vUdu8/KOGDBlarvC370Wb12rk0dw/Qp4IJw10kpTQNIvS4H8moyX2g8FTorqRqZ5hEyLqfwNgjS+FOH++OCG3L5/DdvznXELX91Kr7AeDsQo716/1VEqvWr4tQDgGA==,iv:3Ry5swSJ+8lkUWSCY/XHRGFUgKgO7lQ/Q6p0S72ONqY=,tag:s5ZTTpBWnydmdxFG/lqUhA==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:M1t3IW67SlJs/ZNKDQ==,iv:IdKXHx4Nil5e5KW+il1yFP1kbWWD3Rvb65lrMdfsMaY=,tag:eAtW6m5QALuGYaFxhESe5g==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:V0O0vZzGur/kN133771ZTLe8W1K7HQ==,iv:4vT34PQ/6STvDNPSLGwCpbR/D7bhlsObsiCi7DL9BHQ=,tag:+8EOxboXhyPON7gmAs/7OQ==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:ZWF8LmB3ypS/PDuwQwgZzwddp7mno4BBy0KYV4xwpzwF6MW2,iv:3+7Z37zz8+xMVWd+5qLBZue98bcHKWUfhGyu+Ifvz7Q=,tag:/xLEI1A0mSHfAdZZkz3Gkw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19ufzusf8ls394p4kl5498myl24w7x6ggc5w9grq4tk8dcyh709ls6ku97r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmamVzTUFaZ1A0T1VrdVV6
            eUtzeWV0UUdabmdvVG0zdWkxT3pjSy9pVlY4Cmt1VUY5WVdtLzVnRzUvNDc0QmhK
            RkFRZFVVSExjYmNtSkRNR1dhSXlOcEUKLS0tIHpPOHZXa1RzaG05L2tmWUxKZC8w
            S080VWdjbHh2cnBGNkMvdGt2bzA2OTQKRAuspryST38swQ1W5k6lcD91Euljfi/J
            W56B6Xrq1K9UfsB/ugFNSuaNhBi2b5TWkEcRgeeSorx8ha/GFP10Bg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-04-14T13:33:05Z"
    mac: ENC[AES256_GCM,data:DaaEBhxS2XIr+DSTGnB0xpBBUINb5Z3ioicSVmhiTF3jWjju0JMnfd6iOEnKn3nh95p5N+l2HoVhtyBmQWKK5wqH2APFI3a/YEZ0Ls941s9/ySloJCS9/T7BI9rPLi2vr2qInnKOIGmvkwO/+n6BK5t4L1HNI5QF+auVPqTezBg=,iv:NL3cq7s+dlrYi7qHzPRmFFv9OSbTjqzeb42NtYHgXaQ=,tag:J9Ts3+L2kPh08CMA6iYZhw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
