apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets-user
    namespace: flux-system
stringData:
    SECRET_TRUENAS_API_KEY: ENC[AES256_GCM,data:OPesQf8Yu0Dff2swYGbBXXY80nVKdfPYduBlT+GQ4h7z4gJj+sXorlrCKudVpI94tISwrlPI96+TbahpfoPu3Yn6,iv:tjaE4DFEo6AjMxVpUQiSiEG4wpsddt10cCqNhOKkgus=,tag:NuKubOKgVT9WWEGLGbTzNA==,type:str]
    SECRET_POSTGRES_PASSWORD: ENC[AES256_GCM,data:iOcMMKHJ8kc5NvpNaKAOp0ugNcEAN2fgxcNjdQ==,iv:i8CmPuhC3nvVYYyoWT3YCmtj5FT3x8PriQmsjpW4LRE=,tag:wUKiC59Ha45wMXmqSEjbGA==,type:str]
    SECRET_MONGODB_PASSWORD: ENC[AES256_GCM,data:q4hyqYUmmER+cqL1vzNnV5DcxSZ3431Q6C3BPQ==,iv:6PfN0hm5DrGfC8G2tHu2kep3a0/YsU0ei8FZlggNU8s=,tag:e/mpqJJvfFxJhF8UDjHG8A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19ufzusf8ls394p4kl5498myl24w7x6ggc5w9grq4tk8dcyh709ls6ku97r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4Mm9sekFXV0NzT2JTZVJF
            ZmJSRHhhNktaaXpoVkNjai80WDM0SmNWalYwCkZ1NjVHc2w0UWNIYTNqY1VGK3o4
            bVQzRFFhKy8zMDNBdm00bi9HdElMeDgKLS0tIFJKRUhzWkFUYTFPdGpoSmsreFdk
            TGI5MmVNV0tDWHo2VVgvYUk2bDV3S1EKtB9QrDpZmCTY/v3aCiZCaOdofox243mJ
            Vp91rFhph+soi5jt9pj9PBrfqDRX0UXwqauO9QWvw1m6aiZKGnNi7Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-05-02T07:18:57Z"
    mac: ENC[AES256_GCM,data:Ssp9PRbFeOFZmSiBUVThL+sImHGYQXM3E8OqSisfzo6Xjy/tw+mjdoOkqd41RIwYPay98NTbKZeWABEmS/1ImqKD9uu91PX3h2KRIiUQKQW7oZ8+e0WIjxL2YL1l1wxHzk0Km6PeIehq6tJY2cbY7cnGxPF7lGnlTZftE5aY1Iw=,iv:FckabRI2haq15ehyKG3kzvNjZ2wZolvneR8WTn7WQCk=,tag:ZsR5+fhTpTSTuPWkMwbXkw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
