apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_EXAMPLE: ENC[AES256_GCM,data:v1k+uOABfV1JF7nCbZ7TOqaWy42sREo++9y+IX7KYUlqchTj55daHC0ff31rpsyYZjVTOZ31D1JZilyHLh4D2MSPTflMPPNSgQy9db8wzBAmxLhYWx1yIZhxFMrSzg==,iv:aziwXoKppIIWTpD35+cMOsDqUzFT5r6++BP56Jkl1NU=,tag:c33nBEuGRSyd3C19ehwR5A==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:Sq/IXLAo/tCeORYrXg==,iv:mtDNw5qH+ilnorjIsJ9X7MnhLo5nIqfBhB34kSIoZzw=,tag:7pXFfHldnL0TIxx83x0IuQ==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:Tf7CMx+9nzH8G+7HakLJaZCW4GjjkA==,iv:wcoz5i/sWDCxEXREgZuAsCe2K1BGse++vI8fGGO3Tvk=,tag:GA2S8emkZTs+FKbWz9hIMA==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:eSiGfFBhGYGSk+UzjD7DxTrl9aUwRkgCxuZ4T0I/uphoener,iv:vPRdSwhCPpIp2MQ1NBMHVy0MpAd1vTO+E4PpZMICQqo=,tag:TTE1pgvvAiEIZtSnvgr9lg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19ufzusf8ls394p4kl5498myl24w7x6ggc5w9grq4tk8dcyh709ls6ku97r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsRWxuVXZYTlU1VzhPZTRn
            dzEvWS9UOEFoc04vY25XRWZYY2ZDYm12cEFZCmh6c1VoWlNwTy9VS250bHVFcG5U
            NWpLenJCeXFPQzlBeHlYVHptZEZ3c1kKLS0tIGd5RXNOYUcyU3lhdWdaQVplbzg1
            ZEVYcVJXaVRjVjVGNUozeEY4MGF1MEkKObLWRMeQOvJn0uQ0XZHloiHbqrZ4GGxf
            oujyoPAJ6qWVJrbeOQ//ox/YSVQqsTqzDUFtDhd5+UFacq11IIrGjA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-04-14T10:21:12Z"
    mac: ENC[AES256_GCM,data:M6qLSL7PP2p7Wd0uBsbxQWsHoYpcOdVRwX7m99KUDuQAOT1c+qS5+LTQwo8N2C0RAt5FrXeZmIHzDkkdavAqq240TYqc7WEJ7eo0NRopfZBrdQaJS/zypF6nw7r0QHnrpuJpqsOdA2sDiMDd37DcVYbAQK8PEbyqJpiI0i4DvwE=,iv:7V2/SDRFTb01R1PzjcOZ5poIZuqSghIT04wC/zj2mmw=,tag:TEhWwmrO8YVp0ijTjOoBmg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
