apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets-user
    namespace: flux-system
stringData:
    SECRET_EMAIL: ENC[AES256_GCM,data:nCWRfrJYpb+zhWQG3kCV+oLsDohvvQ==,iv:AGCQXTAP8KyN61QpcsLMhaxo2Jrlwy/gof1myPxjjWc=,tag:AG35l5mWGrTV055lKhtWkA==,type:str]
    SECRET_EMAIL_USER: ENC[AES256_GCM,data:jnr8aCMbkvuiD92HeILU,iv:e58fiLdhL5C5Dsh9YJZgQkMMBxW8MLkO0k7uPXX8ork=,tag:qolILRsXYKRGUka1+xJtHA==,type:str]
    SECRET_EMAIL_DOMAIN: ENC[AES256_GCM,data:d5nfIKtxpRIz,iv:2S7QXPZoBARq1NDc79DvIbiT+9Ah7f6jeli6tiFBsQ4=,tag:WAleemNd3tMuA2ycevpnmQ==,type:str]
    SECRET_EMAIL_SERVER: ENC[AES256_GCM,data:8tUJmBdAGaMcDwuY95Y=,iv:ngjhwLVcjpvCR2N0YAMzs9szqWcQBtIiWH0jSCzL7hw=,tag:+OI5qv2frCvCGpG2RVUUlQ==,type:str]
    SECRET_TRUENAS_API_KEY: ENC[AES256_GCM,data:OPesQf8Yu0Dff2swYGbBXXY80nVKdfPYduBlT+GQ4h7z4gJj+sXorlrCKudVpI94tISwrlPI96+TbahpfoPu3Yn6,iv:tjaE4DFEo6AjMxVpUQiSiEG4wpsddt10cCqNhOKkgus=,tag:NuKubOKgVT9WWEGLGbTzNA==,type:str]
    SECRET_MONGODB_PASSWORD: ENC[AES256_GCM,data:AGVNjRGQU8YMtIvWTKqLTKS6Nxo=,iv:i2MjA3iqDHYEpgv0PGYdXmyr1avdHeg/TNd9aex5aWc=,tag:E7ljGUvk5R+1GZNPXLLttA==,type:str]
    SECRET_POSTGRES_PASSWORD: ENC[AES256_GCM,data:iEd/2wqc8dCaBkRg5xHJbvtcbn0=,iv:N1jZOKc5CRihOgIs+oSa571BYUY7xaqG5TKgZSAoY5w=,tag:XFYlr6HAHK4gaCEjfo1tHg==,type:str]
    SECRET_REDIS_PASSWORD: ENC[AES256_GCM,data:J1m37k+0x5N17neq40n9MpuVGMU=,iv:plt6rLGtdeWdPNpH7DGGw+5vbJ3zW1Idp8QgTPYsh00=,tag:zYcFPNIqKSKA5pGarg5hqw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19ufzusf8ls394p4kl5498myl24w7x6ggc5w9grq4tk8dcyh709ls6ku97r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4Mm9sekFXV0NzT2JTZVJF
            ZmJSRHhhNktaaXpoVkNjai80WDM0SmNWalYwCkZ1NjVHc2w0UWNIYTNqY1VGK3o4
            bVQzRFFhKy8zMDNBdm00bi9HdElMeDgKLS0tIFJKRUhzWkFUYTFPdGpoSmsreFdk
            TGI5MmVNV0tDWHo2VVgvYUk2bDV3S1EKtB9QrDpZmCTY/v3aCiZCaOdofox243mJ
            Vp91rFhph+soi5jt9pj9PBrfqDRX0UXwqauO9QWvw1m6aiZKGnNi7Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-05-12T21:05:39Z"
    mac: ENC[AES256_GCM,data:WUt8oAJ92t0WwevPCGBQxzNkDhC+PoRIwvk+cA0D5bf1POVNSKL/Hi/UOK3+/q3WV772em5XbWGGh0TUvnqJNf239Tej+ZkYV9/ApPaznFWfN/C9QHFvJtb8RaBST+YkZx20zFXCPyarVrfLd4Hp9x8TnkW77EwHZXfKFp2JreU=,iv:17pmF1UDng7znG1Z4nbrNFY/uMzGy5q37bL4qA2mIy0=,tag:cmWvm7Gfhp+1VbxzV1sX7g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
