apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_EXAMPLE: ENC[AES256_GCM,data:5piScIlab+LqS5lhe34TQMzrYba+uaqUEEuvCEKIQxgOwYD9TqW61SdEuCbAtxS+06PS5EdFEx2xVPrgqDqkV7LWNQGPFNFBeBrF5D5EeXlJSPpmRM7iAheaCzPgCA==,iv:YJ7vAPacoNyx2IkECTz7duU88GB2NlpiF/IIJx/xIKk=,tag:KtAbfe31TLO37b8353ilAQ==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:IkVq2fq2VMg=,iv:M1WvSOi/5j8EHc49IHggi+Zt8YXcgduFFW9uUpB8ZcU=,tag:Ng8I+zwMLLVPrTkfzhtKjw==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:VmMLjAbNa2T8fVtIj+HDZT88LdPL1g==,iv:lur6wM8SIzY/Xxtbn9yneiQ3S7dmLMvwFRM4UoC/tss=,tag:+ppbZiz9YvcfGCyHXZd/5g==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:gGkli99z1fRIoLGq9wOaolNEAVEFc6BUdhr3QhRmuNC0f9Xy,iv:brH4eFdcrxrOVIJt/hzOsj1KK6yndbqi1T9jSL4fQ4M=,tag:Tor3A/zm7alTeoZOBiGyow==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19ufzusf8ls394p4kl5498myl24w7x6ggc5w9grq4tk8dcyh709ls6ku97r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOVkJhdXh2RXNZR2ZMYUV4
            MVVPVGx2dGRud2hxc2NxQkFaNldGYTVBMkJvCk5iRzNUOUx4OHEzcEorNGRyVE1o
            U1dlUHd0VFNUMTJMeEduUVdoSHg1dHcKLS0tIHIrVTFGc1QrNHNrQUNjYzR6a1Fs
            V2pSQmdxdDV3aWVBQWJITzlVT0poMkkKurhF05cBAHuDyjChBAsxzOHsLoyR+KyH
            fQwlV85YMA5OhV3prJcagKiPs/0MbdQPoRr45oemGFiYu5D19x7DLQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-04-14T22:27:34Z"
    mac: ENC[AES256_GCM,data:enfDGuUh5NA88TAd/L55VzFCoSGNmE1dLOoNNvppTXbq9mZEKZhtAdOrr/NVmvRG8gYJy1DsFuDEzcIVUY2XQbt0QWzq6SB0ROIjikiTVU4+a6D7fMQMnF86hmvrqAKsUEOPpeYYCfYi/b8Tj33vIcR91pgjGdqH5gjiXA+09hw=,iv:o2LJ+xKswHu5dOfLK9KpQ7nmj+KxOLCKW2hhjaiQzAk=,tag:RNM3Z2AhJyQKjTw+E91N6w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
