apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets-user
    namespace: flux-system
stringData:
    SECRET_TRUENAS_API_KEY: ENC[AES256_GCM,data:OPesQf8Yu0Dff2swYGbBXXY80nVKdfPYduBlT+GQ4h7z4gJj+sXorlrCKudVpI94tISwrlPI96+TbahpfoPu3Yn6,iv:tjaE4DFEo6AjMxVpUQiSiEG4wpsddt10cCqNhOKkgus=,tag:NuKubOKgVT9WWEGLGbTzNA==,type:str]
    SECRET_POSTGRES_PASSWORD: ENC[AES256_GCM,data:iEd/2wqc8dCaBkRg5xHJbvtcbn0=,iv:N1jZOKc5CRihOgIs+oSa571BYUY7xaqG5TKgZSAoY5w=,tag:XFYlr6HAHK4gaCEjfo1tHg==,type:str]
    SECRET_MONGODB_PASSWORD: ENC[AES256_GCM,data:AGVNjRGQU8YMtIvWTKqLTKS6Nxo=,iv:i2MjA3iqDHYEpgv0PGYdXmyr1avdHeg/TNd9aex5aWc=,tag:E7ljGUvk5R+1GZNPXLLttA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19ufzusf8ls394p4kl5498myl24w7x6ggc5w9grq4tk8dcyh709ls6ku97r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4Mm9sekFXV0NzT2JTZVJF
            ZmJSRHhhNktaaXpoVkNjai80WDM0SmNWalYwCkZ1NjVHc2w0UWNIYTNqY1VGK3o4
            bVQzRFFhKy8zMDNBdm00bi9HdElMeDgKLS0tIFJKRUhzWkFUYTFPdGpoSmsreFdk
            TGI5MmVNV0tDWHo2VVgvYUk2bDV3S1EKtB9QrDpZmCTY/v3aCiZCaOdofox243mJ
            Vp91rFhph+soi5jt9pj9PBrfqDRX0UXwqauO9QWvw1m6aiZKGnNi7Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-05-02T13:24:20Z"
    mac: ENC[AES256_GCM,data:u94uw2Lj/LzbKEC6TDbssnwccIp5O7e/RST3901k94bLb2XY7JWQhncT49kG8ikc8XHHsX7KJsOsAuBMJWm4HfINagFXfBsS5p4mxgIeItBBZU6HS0BNbt60kC/EPn1sDyVudFN680Fsm9zEEAL+Vry1XAQ0h30TPvijta0PaFA=,iv:E3RjT2MmcMUHtJ3V5TCq6YUErhsI9crlZlyxliHhVgE=,tag:0Frsp88kjgU1ustndaPMFQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
