---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  TIMEZONE: "Europe/Rome"
  CLUSTER_CIDR: "10.69.0.0/16"
  NODE_CIDR: "10.17.1.0/24"
  TRUENAS_ADDR: "10.17.1.2"
  #
  SVC_MONGODB_ADDR: "10.17.1.211"
  SVC_VLMCSD_ADDR: "10.17.1.209"
