---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: plex
spec:
  chart:
    spec:
      chart: app-template
      version: 3.7.1
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  interval: 30m
  dependsOn:
    - name: openebs
      namespace: openebs
  values:
    controllers:
      plex:
        pod:
          securityContext:
            runAsUser: 2000
            runAsGroup: 2000
            fsGroup: 2000
            fsGroupChangePolicy: "OnRootMismatch"
            supplementalGroups:
              - 44
              - 109
              - 100 # NAS: users
              - 1003 # NAS: nfs-user

        containers:
          app:
            image:
              repository: ghcr.io/onedr0p/plex
              tag: 1.41.4.9463-630c9f557@sha256:1d7589538a85a48ed3c14703b33ae8bacda7ca7db5307c68e8bc1b8ae6e888de
            env:
              PLEX_ADVERTISE_URL: https://10.17.1.199:32400,https://{{ .Release.Name }}.aresu.eu:443
              PLEX_NO_AUTH_NETWORKS: 10.69.0.0/16
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /identity
                    port: 32400
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes
              startup:
                enabled: true
                spec:
                  failureThreshold: 30
                  periodSeconds: 10
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop:
                  - ALL
            resources:
              requests:
                cpu: 100m
              limits:
                # gpu.intel.com/i915: 1
                memory: 2Gi

    service:
      app:
        controller: plex
        type: LoadBalancer
        annotations:
          lbipam.cilium.io/ips: 10.17.1.199
        ports:
          http:
            port: 32400
          # dlna:
          #   port: 1900
          #   protocol: UDP
          # gdm-discovery-1:
          #   port: 32410
          #   protocol: UDP
          # gdm-discovery-2:
          #   port: 32412
          #   protocol: UDP
          # gdm-discovery-3:
          #   port: 32413
          #   protocol: UDP
          # gdm-discovery-4:
          #   port: 32414
          #   protocol: UDP
          # dlna-plex:
          #   port: 32469
          #   protocol: TCP

    ingress:
      app:
        annotations:
          nginx.ingress.kubernetes.io/backend-protocol: HTTPS
        className: external-nginx
        hosts:
          - host: "{{ .Release.Name }}.aresu.eu"
            paths:
              - path: /
                service:
                  identifier: app
                  port: http

    persistence:
      config:
        existingClaim: plex-config
        advancedMounts:
          plex:
            app:
              - path: /config
      plex-cache:
        existingClaim: plex-cache
        advancedMounts:
          plex:
            app:
              - path: /config/Library/Application Support/Plex Media Server/Cache
      logs:
        type: emptyDir
        advancedMounts:
          plex:
            app:
              - path: /config/Library/Application Support/Plex Media Server/Logs
      media:
        type: nfs
        server: "${TRUENAS_ADDR}"
        path: /mnt/tank/media
        advancedMounts:
          plex:
            app:
              - path: /media
      transcode:
        type: emptyDir
        advancedMounts:
          plex:
            app:
              - path: /transcode
