---
# yaml-language-server: $schema=https://k8s-schemas.bjw-s.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name crunchy-postgres-r2
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: crunchy-postgres-r2
    template:
      data:
        CPGO_R2_ENDPOINT: "{{ .cloudflare_cpgo_endpoint }}"
  dataFrom:
    - extract:
        key: Cloudflare
      rewrite:
        - regexp:
            source: "[^a-zA-Z0-9 -]"
            target: "_"
        - regexp:
            source: "(.*)"
            target: "cloudflare_$1"
