---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/observability.giantswarm.io/silence_v1alpha2.json
apiVersion: observability.giantswarm.io/v1alpha2
kind: Silence
metadata:
  name: mikrotik-wap-ax-memory-usage
spec:
  matchers:
    - name: alertname
      value: MikrotikHighMemoryUsage
    - name: routerboard_name
      value: wAP-ax