---
originRequest:
  originServerName: ingress-ext.aresu.eu

ingress:
  - hostname: aresu.eu
    service: &svc https://cilium-gateway-external.kube-system.svc.cluster.local
  - hostname: "*.aresu.eu"
    service: *svc
  - service: http_status:404
