---
ingress:
  - hostname: aresu.eu
    service: https://nginx-external-controller.network.svc.cluster.local:443
    originRequest:
      originServerName: "ingress-ext.aresu.eu"
  - hostname: "*.aresu.eu"
    service: https://nginx-external-controller.network.svc.cluster.local:443
    originRequest:
      originServerName: "ingress-ext.aresu.eu"
  - service: http_status:404
