---
networks:
  - apps
services:
  traefik:
    command:
      - --api.dashboard=true
      - --api.insecure=true
      - "--certificatesresolvers.le.acme.email=${EMAIL}"
      - --certificatesresolvers.cf.acme.caserver=https://acme-v02.api.letsencrypt.org/directory
      - --certificatesresolvers.cf.acme.dnsChallenge.delayBeforeCheck=0
      - --certificatesresolvers.cf.acme.dnsChallenge.provider=cloudflare
      - --certificatesresolvers.cf.acme.dnsChallenge.resolvers=1.1.1.1:53
      - --certificatesresolvers.cf.acme.storage=/certs/acme.json
      - --entryPoints.web.address=:80
      - --entryPoints.web.http.redirections.entryPoint.scheme=https
      - --entryPoints.web.http.redirections.entryPoint.to=websecure
      - --entryPoints.websecure.address=:443
      - --entrypoints.websecure.http.tls=true
      - --entrypoints.websecure.http.tls.certResolver=cf
      - --entrypoints.websecure.http.tls.domains[0].main=*.aresu.eu
      - --providers.docker=true
      - --providers.docker.exposedByDefault=false
      - --providers.docker.network=apps

      # ... other command arguments ...
      - "--accesslog=true" # Enable access logs to stdout

      # Optionally change format or output file (requires volume)
      - "--accesslog.format=json"
      - "--accesslog.filepath=/path/to/access.log"

      # Optionally filter logs
      - "--accesslog.filters.statuscodes=400-599"
    container_name: traefik
    environment:
      CF_DNS_API_TOKEN: ${TRAEFIK_CF_DNS_API_TOKEN}
      TRAEFIK_API_BASICAUTH_HTPASSWD: "${TRAEFIK_API_BASICAUTH_USER}:${TRAEFIK_API_BASICAUTH_PASSWORD}"
      EMAIL: ${EMAIL}
    image: traefik:v3.6.9
    labels:
      # Enable self‑routing
      - "traefik.enable=true"

      # Dashboard router
      - "traefik.http.routers.dashboard.rule=Host(`traefik-dashboard.aresu.eu`)"
      - "traefik.http.routers.dashboard.entrypoints=websecure"
      - "traefik.http.routers.dashboard.service=api@internal"
      - "traefik.http.routers.dashboard.tls=true"

      # Basic‑auth middleware
      - "traefik.http.middlewares.dashboard-auth.basicauth.users=${TRAEFIK_API_BASICAUTH_USER}:${TRAEFIK_API_BASICAUTH_PASSWORD}"
      - "traefik.http.routers.dashboard.middlewares=dashboard-auth@docker"
    networks:
      - apps
    ports:
      - 8099:80
      - 4439:443
      - 8899:8080
    volumes:
      - acme:/certs
      - /var/run/docker.sock:/var/run/docker.sock:ro
volumes:
  acme:
