---
configs:
  rules.yml:
    content: |
      # api:
      #   insecure: true
      # entryPoints:
      #   web:
      #     address: ":80"
      # providers:
      #   docker: {}
      http:
        routers:
          truenas:
            entrypoints:
              - websecure
            rule: "Host(`truenas.aresu.eu`)"
            tls: true
            service: truenas
        services:
          truenas:
            loadBalancer:
              servers:
                - url: http://10.17.1.2:81
              passHostHeader: true
networks:
  apps:
    name: apps
    # external: false
services:
  traefik:
    configs:
      - source: rules.yml
        target: /etc/traefik/rules.yml
    command:
      - --api.dashboard=true
      - --api.insecure=true
      - --certificatesresolvers.cf.acme.caserver=https://acme-v02.api.letsencrypt.org/directory
      - --certificatesresolvers.cf.acme.dnsChallenge.delayBeforeCheck=0
      - --certificatesresolvers.cf.acme.dnsChallenge.provider=cloudflare
      - --certificatesresolvers.cf.acme.dnsChallenge.resolvers=1.1.1.1:53
      - --certificatesresolvers.cf.acme.email=${EMAIL}
      - --certificatesresolvers.cf.acme.storage=/certs/acme.json
      - --entryPoints.web.address=:80
      - --entryPoints.web.http.redirections.entryPoint.scheme=https
      - --entryPoints.web.http.redirections.entryPoint.to=websecure
      - --entryPoints.websecure.address=:443
      - --entrypoints.websecure.http.tls=true
      - --entrypoints.websecure.http.tls.certResolver=cf
      - --entrypoints.websecure.http.tls.domains[0].main=*.aresu.eu
      - --providers.docker=true
      - --providers.docker.exposedByDefault=false
      - --providers.docker.network=apps
      - --providers.file.directory=/etc/traefik
      # - --providers.file.watch=true

      - --log.level=INFO
      - --accesslog=true # Enable access logs to stdout
    container_name: traefik
    environment:
      CF_DNS_API_TOKEN: ${TRAEFIK_CF_DNS_API_TOKEN}
      TRAEFIK_API_BASICAUTH_HTPASSWD: "${TRAEFIK_API_BASICAUTH_USER}:${TRAEFIK_API_BASICAUTH_PASSWORD}"
      EMAIL: ${EMAIL}
    image: traefik:v3.6.9
    labels:
      # Enable self‑routing
      - "traefik.enable=true"

      # Dashboard router
      - "traefik.http.routers.dashboard.rule=Host(`traefik.aresu.eu`) && PathPrefix(`/dashboard`)"
      - "traefik.http.routers.dashboard.entrypoints=websecure"
      - "traefik.http.routers.dashboard.service=api@internal"
      - "traefik.http.routers.dashboard.tls=true"

      # Basic‑auth middleware
      - "traefik.http.middlewares.dashboard-auth.basicauth.users=${TRAEFIK_API_BASICAUTH_USER}:${TRAEFIK_API_BASICAUTH_PASSWORD}"
      - "traefik.http.routers.dashboard.middlewares=dashboard-auth@docker"
    networks:
      - apps
    ports:
      - 8099:80
      - 4439:443
      - 8899:8080
    volumes:
      - acme:/certs
      - /var/run/docker.sock:/var/run/docker.sock:ro
volumes:
  acme:
