---
configs:
  traefik.yaml:
    content: |
      api:
        dashboard: true
      log:
        level: DEBUG
      entryPoints:
        web:
          address: ":80"
          http:
            redirections:
              entryPoint:
                to: websecure
                scheme: https
        websecure:
          address: ":443"
          asDefault: true
          http:
            tls: {}
      serversTransport:
        insecureSkipVerify: true
      providers:
        docker:
          endpoint: "unix:///var/run/docker.sock"
          exposedByDefault: false
        file:
          directory: /etc/traefik/dynamic
      certificatesResolvers:
        cloudflare:
          acme:
            email: ${EMAIL}
            storage: /certs/acme.json
            caServer: https://acme-v02.api.letsencrypt.org/directory
            dnsChallenge:
              provider: cloudflare
              propagation:
                # Fixes issues with cloudflare propagation of the TXT record by just waiting instead of checking
                disableChecks: true
                delayBeforeChecks: 60s
              resolvers:
                - "1.1.1.1:53"
                - "1.0.0.1:53"
  truenas.yaml:
    content: |
      http:
        routers:
          truenas:
            entryPoints:
              - websecure
            rule: "Host(`truenas.aresu.eu`)"
            tls: {}
            service: truenas
        services:
          truenas:
            loadBalancer:
              servers:
                - url: http://10.17.1.2:81
              passHostHeader: true
networks:
  proxy:
    name: proxy
services:
  traefik:
    configs:
      - source: traefik.yaml
        target: /etc/traefik/traefik.yaml
      - source: truenas.yaml
        target: /etc/traefik/dynamic/truenas.yaml
    container_name: traefik
    environment:
      CF_DNS_API_TOKEN: ${TRAEFIK_CF_DNS_API_TOKEN}
      TRAEFIK_API_BASICAUTH_DASHBOARD: "${TRAEFIK_API_BASICAUTH_DASHBOARD}"
      EMAIL: ${EMAIL}
    image: traefik:v3.6.10
    labels:
      - traefik.enable=true
      - traefik.http.routers.dashboard.rule=Host(`traefik.aresu.eu`)
      - traefik.http.routers.dashboard.entryPoints=websecure
      - traefik.http.routers.dashboard.service=api@internal
      - traefik.http.routers.dashboard.middlewares=dashboard-auth
      - traefik.http.middlewares.dashboard-auth.basicauth.users=${TRAEFIK_API_BASICAUTH_DASHBOARD}
    networks:
      - proxy
    ports:
      - 80:80
      - 443:443
    volumes:
      - acme:/certs
      - /var/run/docker.sock:/var/run/docker.sock:ro
volumes:
  acme:
