apiVersion: v1
kind: Secret
metadata:
    name: paperless-secret
    namespace: home-cloud
stringData:
    PAPERLESS_DBENGINE: ENC[AES256_GCM,data:O9vrjhl4vB4=,iv:6ETbfeHoKkADw9cR+gHNwpJGnVApcVIK+zUJeNiWvl0=,tag:xjC9iLm/cEhpZu0zeb0D9A==,type:str]
    PAPERLESS_DBHOST: ENC[AES256_GCM,data:RBAusmMNGmMbIaa7wAZMya3u0WBJyS2FcSp5DxCh7UMeUFqIwg==,iv:tTejuLSz5VjvNt0GyDMsoM5jsn37lBukBwKewkcN2Qc=,tag:LEsj9y/kHMfP86aI+M8CUA==,type:str]
    PAPERLESS_DBPORT: ENC[AES256_GCM,data:RrQzVA==,iv:AAV1EZ2hQEpg/7pf0u7KZ5fsQdNGpWrF3SMCWjhwX98=,tag:R121qE02lxPGyzkLDEsb1g==,type:str]
    PAPERLESS_DBNAME: ENC[AES256_GCM,data:tGi1a7RRDCNg,iv:vKFoAWX3URKk4lmfaqC2akND/v/JB3bOv+GkBh6ZUJY=,tag:ryji/QrWWhRjH7WYK5ve/Q==,type:str]
    PAPERLESS_DBUSER: ENC[AES256_GCM,data:s9FH6z+smmxT,iv:6s9RUC30ACxKLEFq86ymIGMT2mXfahgM7/s6Zlzy/nk=,tag:HT3tWbeEhRkhGW/ZgeHpKQ==,type:str]
    PAPERLESS_DBPASS: ENC[AES256_GCM,data:XcTNAZizDKwLgmdF8e5JewGL2KY=,iv:P6cux929KrwehiiPVcZ76RYPxZHOdsHQl8+VRvnPa10=,tag:WMC7VCyd5HazqhQdxdrdGg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19ufzusf8ls394p4kl5498myl24w7x6ggc5w9grq4tk8dcyh709ls6ku97r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnd0NrZVFIeitETENFOVRp
            a2txRXhPc2Q5MVE0NnNsenhWMFAwNVpFbVRvClE3V25JRjdrRUdRYzVubVo2QldU
            Qms3YkNhL0sxNzY4RUluYXM1ZG0yWWsKLS0tIEV4M0FuUlh1aDBsMzN0OGZEMDFj
            Sm0vd1lOSkNmemVlRFNWK2VOcUNqVzQKvJUmTA23thBOYW3tMY7QwpaFPW+Su/t3
            8Tcim5b+IywF1ubQCQmecQff4Z/bLp4kuRsTs3447jhorFQr+FNjTQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-05-06T13:01:43Z"
    mac: ENC[AES256_GCM,data:t/w5CmZA4IbxwMVM5FhvmIUvV00QdB/o+jvzMoJHhX/VcG1nQjtrWJAD3c9aAheBCr+I6pVfOgqaKv8kdUmav8t3n77WeFdXAU0vQKD1byPUNS9A1QlujPk0sjrFaRNoARgMDp3h6syiP7fd0pKForxhA/xLY1krA8t5V0snl5k=,iv:rWwBwLczJ4Xs4r5iuGmegAxem1N8kRafk6+LQhJEoZM=,tag:TbGjdCRifMS0hiMirh7OGQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
