---
# yaml-language-server: $schema=https://raw.githubusercontent.com/budimanjojo/talhelper/master/pkg/config/schemas/talconfig.json
clusterName: &clusterName home-ops

endpoint: https://10.17.1.8:6443

# renovate: depName=ghcr.io/siderolabs/installer datasource=docker
talosVersion: v1.9.4
# renovate: depName=ghcr.io/siderolabs/kubelet datasource=docker
kubernetesVersion: v1.32.2

additionalApiServerCertSans: &sans
  - &talosControlplaneVip 10.17.1.8
  - 127.0.0.1 # KubePrism
additionalMachineCertSans: *sans

# Disable built-in Flannel to use Cilium
cniConfig:
  name: none

nodes:
  - hostname: kube-bmax-01
    ipAddress: 10.17.1.34
    installDiskSelector:
      model: UDSS UD2CS1HT100 # M.2 SATA
      # model: TOSHIBA MK2546GS # HDD
    # Volume config stub, would need re-init to apply at the current state, see https://github.com/siderolabs/talos/issues/8367#issuecomment-2564476691
    # volumes:
    #   - name: EPHEMERAL
    #     provisioning:
    #       diskSelector:
    #         match: system_disk
    #       maxSize: 50GB
    #       grow: false
    controlPlane: true
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: 00:e0:4c:2e:36:08
        dhcp: true
        vip:
          ip: *talosControlplaneVip
    nodeLabels:
      node.kubernetes.io/virtual: "false"
    # machineDisks:
    #   - device: /dev/sda
    #     partitions:
    #       - mountpoint: /var/mnt/extra
    schematic:
      customization:
        systemExtensions:
          officialExtensions:
            - siderolabs/iscsi-tools
            - siderolabs/util-linux-tools
            # - siderolabs/gasket-driver # Coral
            - siderolabs/i915
            - siderolabs/intel-ucode
            - siderolabs/mei
    patches:
      - &longhorn |-
        machine:
          kubelet:
            extraMounts:
              - destination: /var/lib/longhorn
                type: bind
                source: /var/lib/longhorn
                options:
                  - bind
                  - rshared
                  - rw
        cluster:
          apiServer:
            admissionControl:
              - name: PodSecurity
                configuration:
                  apiVersion: pod-security.admission.config.k8s.io/v1beta1
                  kind: PodSecurityConfiguration
                  exemptions:
                    namespaces:
                      - longhorn

  - hostname: kube-nuc-01
    ipAddress: 10.17.1.38
    installDiskSelector:
      # model: KINGSTON SMS200S
      model: KINGSTON SUV500M # MSATA 200GB
    controlPlane: true
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: 68:5b:35:a1:01:ca
        dhcp: true
        vip:
          ip: *talosControlplaneVip
    nodeLabels:
      node.kubernetes.io/virtual: "false"
    schematic:
      customization:
        systemExtensions:
          officialExtensions:
            - siderolabs/iscsi-tools
            - siderolabs/util-linux-tools
            # - siderolabs/i915 # Too old to be useful
            - siderolabs/intel-ucode
            - siderolabs/mei

  - hostname: kube-proxmox-01
    ipAddress: 10.17.1.36
    installDisk: /dev/sda
    controlPlane: true
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: bc:24:11:41:5f:39
        dhcp: true
        vip:
          ip: *talosControlplaneVip
    nodeLabels:
      node.kubernetes.io/virtual: "true"
    schematic: &pve_schematic
      customization:
        systemExtensions:
          officialExtensions:
            - siderolabs/iscsi-tools
            - siderolabs/util-linux-tools
            - siderolabs/qemu-guest-agent

    patches:
      - &pve_disks |-
        machine:
          disks:
          - device: /dev/sdb
            partitions:
              - mountpoint: /var/lib/longhorn

# Global patches
patches:
  - "@./patches/global/machine-files.yaml"
  - "@./patches/global/machine-kubelet.yaml"
  - "@./patches/global/machine-network.yaml"
  - "@./patches/global/machine-sysctls.yaml"
  - "@./patches/global/machine-time.yaml"

# Controller patches
controlPlane:
  nodeLabels:
    topology.kubernetes.io/region: home
    topology.kubernetes.io/zone: m

  schematic:
    customization:
      extraKernelArgs:
        - apparmor=0 # Less security, more speed
        - init_on_alloc=0 # Less security, more speed
        - init_on_free=0 # Less security, more speed
        - intel_iommu=on # PCI Passthrough
        - iommu=pt # PCI Passthrough
        - mitigations=off # Less security, more speed
        - security=none # Less security, more speed
        - net.ifnames=1 # Enable predictable NIC naming
      # systemExtensions:
      #   officialExtensions:
      #     # - siderolabs/gasket-driver # Coral
      #     - siderolabs/i915
      #     - siderolabs/intel-ucode
      #     - siderolabs/mei

  patches:
    - "@./patches/controller/admission-controller-patch.yaml"
    - "@./patches/controller/cluster.yaml"

    # Enable host dns
    - |-
      machine:
        features:
          hostDNS:
            enabled: true
            resolveMemberNames: true
            forwardKubeDNSToHost: false

    # Enable MutatingAdmissionPolicy
    - |-
      cluster:
        apiServer:
          extraArgs:
            runtime-config: admissionregistration.k8s.io/v1alpha1=true
            feature-gates: MutatingAdmissionPolicy=true

    # Configure NFS mount options
    - |
      machine:
        files:
          - op: overwrite
            path: /etc/nfsmount.conf
            permissions: 0o644
            content: |
              [ NFSMount_Global_Options ]
              nfsvers=4.2
              hard=True
              noatime=True
              nconnect=16

    # Enable K8s Talos API Access
    - |-
      machine:
        features:
          kubernetesTalosAPIAccess:
            enabled: true
            allowedRoles:
              - os:admin
            allowedKubernetesNamespaces:
              - actions-runner-system
              - system-upgrade

    # Configure udev rules
    - |-
      machine:
        udev:
          rules:
            # Intel GPU
            - SUBSYSTEM=="drm", KERNEL=="renderD*", GROUP="44", MODE="0660"
