---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./node-exporter-odroidhc4.yaml
  - ./node-exporter-truenas.yaml
  # - ./smartctl-exporter-odroidhc4.yaml # Disabled until the exporter is re-deployed
  - ./smartctl-exporter-truenas.yaml
