apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:dLAVZHSHsAsHiW2c4slZfIvB9iRWm72ZQMDelxXqFMM=,iv:DhEqqnNVj0dF6eYWORIzviVYrtlpnRxoG/YS0nxV0Cs=,tag:cNmpKaIRBGi67cE5QbpN5w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19ufzusf8ls394p4kl5498myl24w7x6ggc5w9grq4tk8dcyh709ls6ku97r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhUnc4YmUwMVJjeVc3S0dy
            THZhUDlBbmJzTXBpYTR1cWRoTmM5UmxCdDJNCkRKTE9IVjRpVEh2ZXZHdEtRL0dV
            M2x4TzRjRDYzVURjbnR4U1ZVY0F4dDAKLS0tIERYU04zb1p1dmhxdmpRNkFEVml0
            dEVTeUJTNVRySG9UelNSOTVpMi95NHcK5eFE/McezwZ41s5WwZHWrUT5e04tAXfv
            7tBIwezftFkG5DXAsVUGfaYdx2/JPCbXtbcKAeBN96yrZHzmsktn8Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-04-14T13:33:05Z"
    mac: ENC[AES256_GCM,data:4Az7ZjDDoTpqL9Jx7++j2Z4HKzkTsPiBHIguhlgUoGCBxOu4y07b8wFNJwiLHeXE4dgO6WF0ukPztWinrTW4IUPxU8SstielwIBJdhuyna/kQVtexjZew9pXmYiCbbUhpbxRZekmBCNFwBwcS5HJCOYNFsVKRD1DimCUW3H4wco=,iv:FZDUyZYeIOeOR5lhLHjOU/Fy7hrFqAq8cGBV+FXVtcg=,tag:pW24aWVBURP4mGArX3GT/w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
