apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:TRv/uEfMegR82y0SKUi5qqy+6rz79W1OANb0RREa4Ks=,iv:TLeKZvzJq+mRJaWAs8nFn3vXgcj3o/peLWIiyiy89rk=,tag:3CFhrmOvhO+CoPAFeejIRQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19ufzusf8ls394p4kl5498myl24w7x6ggc5w9grq4tk8dcyh709ls6ku97r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGY3RveFZpbXozSThIa29S
            Mm40eC9jMWFXV0t5NlhhMDBmbGVGSkMrazNVCm85TlhNSmlxSXNmRkZPMXBDUFJO
            a1ppQ0t2U1lxS013M1hwNkZnRjUrdlEKLS0tIHNKdWVkeDFnYm5XWGNLc2sxNUNY
            b1hpbGFQVlh4eXp5RWljVURMMHBsQXcK5OYpkKlGCCAEEvmql9agzK7AVnZxFvr2
            Ju+qtN1zHEFH2V+W2pddlwYER36ydFLp3JNeTQrR6UmXRXy1/ZIvSQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-04-14T15:40:17Z"
    mac: ENC[AES256_GCM,data:wYAy21rPfYBygDrU8FtjVJ/TsOGUDImAl6fYe93FZJw7Jr/ZGd/GZnEMTi6wwN3pJx2JqeOPtk48arjzWBZ8SHrqwTB4hvjy9lAC8GX217rAmjygTAw5lb00VvkGsYl4Px0RrsJ2/gQ7eD5FbER72uOntkspKS2+Ui9Xux72k0Q=,iv:GqRl33hUAFEqywVl0Jc9iXUu69aKrdytBh7uZX+oReo=,tag:ULtnmnPITixB96Zy2plPTA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
