apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:BQKoJgDSQmDF8+L9lKsO9X9grGSVEjCjihMRtSuwB/I=,iv:zJyvNlDxIJZHh/aSm5+gy6s7s66NkiyYigM4DMLUGIE=,tag:ZEaDolq0hZLgINm/m6lczg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19ufzusf8ls394p4kl5498myl24w7x6ggc5w9grq4tk8dcyh709ls6ku97r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGUkdDaEczTjc4QldOYTZj
            MTZUK1ltZXEyUEJuVzl4R0NCNEJSTGsyRlNBClIzWk5VNDZQSTNKMW90ZmZRSjhJ
            ODBTKzk0S09nNVh3bExEWmtBN3dvc3cKLS0tIG5KYkMvNFdsdGFWTnhJNkUxQmNi
            Nlp2dnBmWHdxd2h2SVQvQUpYWDRwVXMKd8JO9nIwzTf7IZUw/sRp/CYcNL0RLEe0
            iqgavddr/aPf7ZMguQDquO6A6iKtkmDodUkv4Ny73mYhoAOEaExo3w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-04-14T22:37:52Z"
    mac: ENC[AES256_GCM,data:RVH6cjQnGERIfTHi3uoLpfUc1VZUB0amq2XwbIWJiXXYiU9Sxwv7ZBSoyU71BswjO5JD/q+LkTv8tbnWY82amJJjyRQvD7beuuvEbhfgM+9Y5KyPwJx5ZSD253gEkCxao1shKYQjIhNTf6IiF6ydPf54+5bik0Yk1DvUO3Vul0g=,iv:NtjmRfNTi1rA2fcAiCQH3HflH7T0mTgMaJj40D+4yr8=,tag:hM0Tx0+4W0CPX8tA1yZjhw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
