---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: system-upgrade
components:
  - ../../components/cluster-settings
  - ../../components/flux-alerts
resources:
  - ./namespace.yaml
  - ./tuppr/ks.yaml
