---
# yaml-language-server: $schema=https://k8s-schemas.bjw-s.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: openebs
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: openebs
  values:
    localpv-provisioner:
      # localpv:
      #   basePath: &hostPath /var/mnt/extra/openebs/local
      hostpathClass:
        enabled: true
        name: openebs-hostpath
        isDefaultClass: false
        # basePath: *hostPath

    engines:
      local:
        lvm:
          enabled: false
        zfs:
          enabled: false
      replicated:
        mayastor:
          enabled: false
