---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: openebs
spec:
  interval: 30m
  chart:
    spec:
      chart: openebs
      version: 4.2.0
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: openebs
        namespace: flux-system
  values:
    mayastor:
      csi:
        node:
          initContainers:
            enabled: false # Talos has the nvme_tcp module built-in
          # kubeletDir: &mayastorHostPath /var/local
      etcd:
        replicaCount: 1 # TODO: Increase this to 3 when adding nodes
      io_engine:
        cpuCount: 500m
      storageClass:
        parameters:
          thin: "true"

    engines:
      local:
        lvm:
          enabled: false
        zfs:
          enabled: false
