---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: frigate
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: frigate-secret
    template:
      engineVersion: v2
      data:
        FRIGATE_MQTT_USERNAME: "{{ .MQTT_USERNAME }}"
        FRIGATE_MQTT_PASSWORD: "{{ .MQTT_PASSWORD }}"
        FRIGATE_RTSP_USERNAME: "{{ .RTSP_USERNAME }}"
        FRIGATE_RTSP_PASSWORD: "{{ .RTSP_PASSWORD }}"
        PLUS_API_KEY: "{{ .FRIGATEPLUS_APIKEY }}"
  dataFrom:
    - extract:
        key: frigate
    - extract:
        key: mqtt
