---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: frigate
spec:
  interval: 30m
  chart:
    spec:
      chart: frigate
      version: 7.7.0
      sourceRef:
        kind: HelmRepository
        name: blakeblackshear
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  valuesFrom:
    - kind: ConfigMap
      name: frigate-configmap
      valuesKey: config.yml
      targetPath: config
  values:
    image:
      repository: ghcr.io/blakeblackshear/frigate
      tag: 0.15.0@sha256:dc77295ccc5a7258510ab6b1d9d5b7a339027305e2d29224338534febc4d1e89
    env:
      TZ: ${TIMEZONE}
    envFromSecrets:
      - frigate-secret
    shmSize: 256Mi
    ingress:
      enabled: true
      ingressClassName: internal
      hosts:
        - host: "{{ .Release.Name }}.${SECRET_DOMAIN}"
          paths:
            - path: /
              portName: http-auth
    persistence:
      config:
        enabled: true
        existingClaim: frigate
    extraVolumeMounts:
      - name: media
        mountPath: /media
    extraVolumes:
      - name: media
        nfs:
          server: ${TRUENAS_ADDR}
          path: /mnt/tank/media/frigate
    resources:
      requests:
        cpu: 100m
      limits:
        gpu.intel.com/i915: "1"
        memory: 2Gi
    nodeSelector:
      # google.feature.node.kubernetes.io/coral: "true"
      intel.feature.node.kubernetes.io/gpu: "true"
    # affinity:
    #   podAntiAffinity:
    #     requiredDuringSchedulingIgnoredDuringExecution:
    #       - labelSelector:
    #           matchExpressions:
    #             - key: app.kubernetes.io/name
    #               operator: In
    #               values: ["plex"]
    #         topologyKey: kubernetes.io/hostname
    podAnnotations:
      reloader.stakater.com/auto: "true"
