apiVersion: v1
kind: Secret
metadata:
    name: unifi-controller-secret
stringData:
    MONGO_USER: ENC[AES256_GCM,data:AWzEh4c=,iv:w7FHQ6gVhDhQDUGag5DJnhzg6ku7PmZJbt0D9ihDLBg=,tag:qyZT7O/0uLSj9D5vSovbwg==,type:str]
    MONGO_PASS: ENC[AES256_GCM,data:6V2TQ3NE+EJ36h6Dr/khwGNz7uY=,iv:pOyCDCkN79ediEcN4o6u7Z83O4v76Fq6GIiC/ta9H9E=,tag:tDOOdX1Q4YiH6Ef+h26uyw==,type:str]
    MONGO_HOST: ENC[AES256_GCM,data:1EBpZoR+TmBeu2RqJojUahGDu9Z7/1L+EBpLeQuh+V8NmA==,iv:JIMD4EW+hu/HFpY7Mfoh1DEl7AnjOA8m4uI8xihcScc=,tag:o7HHsbt2NQqMuvJHn67C7w==,type:str]
    MONGO_PORT: ENC[AES256_GCM,data:NE99KBM=,iv:+4Ijs5qG5lek1eGTd54whJS2nnB+mdnjYNyKU308yh4=,tag:IQYT3TdmtlGwfHFvclQuTg==,type:str]
    MONGO_DBNAME: ENC[AES256_GCM,data:tVNhIiw=,iv:A/2tNq0GpplDmcfNE3Um+bPWrxorWKRtxI9P+Y6gFF0=,tag:66xsiJh5GpNH14nu7scafw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19ufzusf8ls394p4kl5498myl24w7x6ggc5w9grq4tk8dcyh709ls6ku97r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmc0wvdjFEb3RmZWtvdjQz
            OWI0Nm50TjJzSjVsV2pZRUI2aUVQTTFUQjFVCncxR0huYWg3eEtrYnROT2JaUWdq
            MURzb3JXZS9XUmY5UzgzRmpEN2dNSmsKLS0tICtzUjdWOHZDWW94NzNYTmwrY1BR
            aDNrMUxpSXRDZGxFTmlycEtIVWhXYjgKWL2QoaF+BMhRHhDQ1RuREz2frFpzRCh5
            GSmrFAWK0Ttmu+1FjFldYRgWhZVd6ZA0GtB3Wiv0IK4bmiTX10lEPg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-05-11T18:29:13Z"
    mac: ENC[AES256_GCM,data:tiGBjbA1xdAe2wnWYskG+LTc1NdG4SqueQQyQukl3c1qjDFVpZwBPbV94bxHseseBdZKTSCpmkY1j+/HDeZ8MFmDiYTZwvvYOkJ46veI5fecqWyGS4tOg5fPZDXk50iT8Efg8ube0VuQV703P/50BX7sRahgWhc08JVeLC2PhZQ=,iv:3GEdbKAPoASC6u6Q5uftCbCUI2rHvs4rtgiyBqUwLHI=,tag:2WG8zFAfgWIlWm/S6cIKiw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
