apiVersion: v1
kind: Secret
metadata:
    name: unifi-controller-secret
stringData:
    DB_URI: ENC[AES256_GCM,data:lFjDngHjGFslr0DZmyIZ1bse5PM/h7m7RBRNxE/pqgI4csY7F4vzgqd13NBHhG1mowmyKengRWO32CySEu8HwHkRjT7oQx0CCy3dV6bVAYIqaRLCiNHDstfl3J+oP1C3s1i58M3OHXXDw2wgEkE=,iv:FQBWQJKjktXQCgKzBv6mAPdrI2G1fYyOxRj3SqCkySM=,tag:kNH5Aivrej5cq1rhBuD9wQ==,type:str]
    STATDB_URI: ENC[AES256_GCM,data:NPK/H0vvzLKvoGYg9Rp5kcf/Yhcmj9FZ6nbqTxNJ1FGxXhgpDXqO7cKqg57EKmO8U5eW303A+ALgCJhSm9wL2bg3Au8l71b1AfPOAOaRp1SUWAHy1+7Np8u2KZ979xrqV6KyUO/7bJugHclKmFK5IgwVYQ==,iv:+2SjpruJapcQw7lcCq0D4k+iQ8PF5gAY+ZNkVzEMjzw=,tag:F5Qad0pjytX5WpOadVQ/uw==,type:str]
    DB_NAME: ENC[AES256_GCM,data:nbTtdNM=,iv:IATHXiLfGSLIrYIMU7vyKPYFcJ6xAeRXn1V9vrTA6hg=,tag:jemjdqjwBi5u9CV1YhHxtg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19ufzusf8ls394p4kl5498myl24w7x6ggc5w9grq4tk8dcyh709ls6ku97r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmc0wvdjFEb3RmZWtvdjQz
            OWI0Nm50TjJzSjVsV2pZRUI2aUVQTTFUQjFVCncxR0huYWg3eEtrYnROT2JaUWdq
            MURzb3JXZS9XUmY5UzgzRmpEN2dNSmsKLS0tICtzUjdWOHZDWW94NzNYTmwrY1BR
            aDNrMUxpSXRDZGxFTmlycEtIVWhXYjgKWL2QoaF+BMhRHhDQ1RuREz2frFpzRCh5
            GSmrFAWK0Ttmu+1FjFldYRgWhZVd6ZA0GtB3Wiv0IK4bmiTX10lEPg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-05-12T12:34:17Z"
    mac: ENC[AES256_GCM,data:1qeZbi5YkmLApj5bUg9NQkjYcWPIpP8xZomgAhbuWRKKKNZC3kr8ZuF/Df+nsZS2T2RwSJNO8zmWIQ70aMM+gJhMR7yv/X3htXa1E3gRFr5xXz6WL/3uw0cWxCWn+IUvg0dD39H768ewouGjNOjbjJLPLejTvsPLpTcP955uY2g=,iv:59LvwxvOHoiAoaLqu+Ip8aLDbwXZVOeoWoi6JvTwcZ0=,tag:t47HiS1U5+Wz3o1OAlFK6A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
