---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: lidarr
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.1.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    controllers:
      lidarr:
        annotations:
          reloader.stakater.com/auto: "true"
        # initContainers:
        #   init-db:
        #     image:
        #       repository: ghcr.io/onedr0p/postgres-init
        #       tag: 16
        #     envFrom: &envFrom
        #       - secretRef:
        #           name: lidarr-secret
        containers:
          app:
            image:
              repository: ghcr.io/onedr0p/lidarr
              tag: 2.2.5.4141@sha256:6eea2458a2b0da20fde3ad18b64f970acde9ede4645b9af89e193ec08b635d09
            env:
              TZ: ${TIMEZONE}
              RADARR__PORT: &port 80
              RADARR__LOG_LEVEL: info
            # envFrom: *envFrom
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /ping
                    port: *port
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 1Gi
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 568
        runAsGroup: 568
        fsGroup: 568
        fsGroupChangePolicy: OnRootMismatch
        supplementalGroups: [1003]
        seccompProfile: { type: RuntimeDefault }
    service:
      app:
        controller: lidarr
        ports:
          http:
            port: *port
    ingress:
      app:
        className: internal
        annotations:
          hajimari.io/enable: "true"
          hajimari.io/group: "media"
          hajimari.io/icon: "music-box"
          hajimari.io/info: "Music"
        hosts:
          - host: "{{ .Release.Name }}.${SECRET_DOMAIN}"
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
    persistence:
      # config:
      #   enabled: true
      #   type: persistentVolumeClaim
      #   existingClaim: lidarr-config-v1
      #   globalMounts:
      #     - path: /config
      tmp:
        type: emptyDir
      music:
        type: nfs
        server: "${TRUENAS_ADDR}"
        path: /mnt/tank/media
        globalMounts:
          - path: /music
            subPath: Music
      downloads:
        type: nfs
        server: "${TRUENAS_ADDR}"
        path: /mnt/tank/downloads
        globalMounts:
          - path: /downloads
            subPath: complete/music
