---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: lidarr
spec:
  chartRef:
    kind: OCIRepository
    name: lidarr
  interval: 30m
  values:
    controllers:
      lidarr:
        annotations:
          reloader.stakater.com/auto: "true"
        pod:
          securityContext:
            runAsUser: 2000
            runAsGroup: 2000
            runAsNonRoot: true
            fsGroup: 2000
            fsGroupChangePolicy: "OnRootMismatch"
            supplementalGroups:
              - 100 # NAS: users
              - 1000
              - 1003 # NAS: nfs-user
        containers:
          app:
            image:
              repository: ghcr.io/home-operations/lidarr
              tag: 3.0.0.4855
            env:
              LIDARR__APP__INSTANCENAME: Lidarr
              LIDARR__AUTH__APIKEY:
                valueFrom:
                  secretKeyRef:
                    name: lidarr-secret
                    key: api_key
              LIDARR__AUTH__METHOD: External
              LIDARR__AUTH__REQUIRED: DisabledForLocalAddresses
              LIDARR__LOG__DBENABLED: "False"
              LIDARR__LOG__LEVEL: info
              LIDARR__SERVER__PORT: &port 8686
              LIDARR__UPDATE__BRANCH: develop
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /ping
                    port: *port
                  initialDelaySeconds: 10
                  periodSeconds: 10
                  timeoutSeconds: 5
                  failureThreshold: 3
              readiness: *probes
            resources:
              requests:
                cpu: 20m
                memory: 384Mi
              limits:
                memory: 2Gi
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop:
                  - ALL
    service:
      app:
        ports:
          http:
            port: *port
    persistence:
      config:
        existingClaim: lidarr-config
      tmpfs:
        type: emptyDir
        globalMounts:
          - path: /tmp
            subPath: tmp
      media:
        type: nfs
        server: truenas.aresu.eu
        path: /mnt/tank/media
        globalMounts:
          - path: /data/media
    route:
      app:
        hostnames:
          - lidarr.aresu.eu
        parentRefs:
          - name: envoy-internal
            namespace: network
            sectionName: https
