---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: lidarr
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.7.2
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  dependsOn:
    - name: longhorn
      namespace: longhorn
  values:
    controllers:
      lidarr:
        annotations:
          reloader.stakater.com/auto: "true"

        pod:
          securityContext:
            runAsUser: 2000
            runAsGroup: 2000
            runAsNonRoot: true
            fsGroup: 2000
            fsGroupChangePolicy: "OnRootMismatch"
            supplementalGroups:
              - 100 # NAS: users
              - 1000
              - 1003 # NAS: nfs-user

        containers:
          app:
            image:
              repository: ghcr.io/nklmilojevic/lidarr-develop
              tag: 2.9.3.4527@sha256:f7169a59d4be082f83dc7a3bbdac663eb21ef57455b87898559b9989e5092b35
            env:
              LIDARR__APP__INSTANCENAME: Lidarr
              LIDARR__AUTH__APIKEY:
                valueFrom:
                  secretKeyRef:
                    name: lidarr-secret
                    key: api_key
              LIDARR__AUTH__METHOD: External
              LIDARR__AUTH__REQUIRED: DisabledForLocalAddresses
              LIDARR__LOG__DBENABLED: "False"
              LIDARR__LOG__LEVEL: info
              LIDARR__SERVER__PORT: &port 8686
              LIDARR__UPDATE__BRANCH: develop
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /ping
                    port: *port
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes
            resources:
              requests:
                cpu: 20m
                memory: 384Mi
              limits:
                memory: 2Gi
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop:
                  - ALL

    service:
      app:
        controller: lidarr
        ports:
          http:
            port: *port

    ingress:
      app:
        className: "internal-nginx"
        hosts:
          - host: lidarr.aresu.eu
            paths:
              - path: /
                service:
                  identifier: app
                  port: http

    persistence:
      config:
        existingClaim: lidarr-config
      add-ons:
        type: emptyDir
      tmp:
        type: emptyDir
      downloads:
        type: nfs
        server: truenas.aresu.eu
        path: /mnt/tank/downloads
        globalMounts:
          - path: /downloads
      books:
        type: nfs
        server: truenas.aresu.eu
        path: /mnt/tank/media/Books
        globalMounts:
          - path: /books
