---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: freshrss
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.7.1
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system

  values:
    controllers:
      freshrss:
        replicas: 1
        strategy: RollingUpdate

        annotations:
          reloader.stakater.com/auto: "true"

        pod:
          securityContext:
            fsGroup: 2000
            fsGroupChangePolicy: "OnRootMismatch"

        containers:
          app:
            image:
              repository: ghcr.io/linuxserver/freshrss
              tag: 1.26.0@sha256:5cccae5854c93c7108b9952c2badaa3677c4e8ceadbb610f476c518c617eaee2
            env:
              PUID: 2000
              PGID: 2000
            resources:
              requests:
                cpu: 5m
                memory: 32Mi
              limits:
                memory: 256Mi

    service:
      app:
        controller: freshrss
        ports:
          http:
            port: 80

    ingress:
      app:
        className: "internal-nginx"
        hosts:
          - host: freshrss.aresu.eu
            paths:
              - path: /
                service:
                  identifier: app
                  port: http

    persistence:
      config:
        existingClaim: freshrss
        globalMounts:
          - path: /config
