apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:H5b/Tim6cJAKSUaXlIuAQ9D5e3kflXs8AwgBdLQTJNcMhndp1MWt2A==,iv:5RY5vxk0wGG4rF/ePVJf0YkkIEl0gGIc/zKdhNN+21o=,tag:H/zi6ovqu1q4kxq4vLCJLg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19ufzusf8ls394p4kl5498myl24w7x6ggc5w9grq4tk8dcyh709ls6ku97r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWNlpZNFZhQ0RwN3Awemp2
            S3dnNGJ1OEVlQXpnL3RpeXQyWTN0M2YxS2drCkVNU3lwMHhuc3dJaHBSNEIxUm5Z
            ZlhZbE8yWVdRL1VBd2o2ZWVwTHVyencKLS0tIHcyQnNHVGVLQmROYk05TVV2YUht
            emNoSFBGRHRpUlFlWitoT0Ywcy9JK1kKlC55LocgfiZM4CoxCVal/nsXLDT+dqrX
            Mtyt9HRE9BWLXRk+QJXF79Wj/4o356gRJf5/azOXkxQEopqB+v1hGw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-04-14T10:21:12Z"
    mac: ENC[AES256_GCM,data:Aw9OIcM0HeWORYFgV2hwrYqRqOCMIiPVRrvh8XBpC3sGEMl/IO+RiRoQMTgD6fobDV7sUJtnbgbK2Yt9TxWVe23UtkJyBltCZFaRnUzRWf3+4o+8E70udvTF0Vgy5PgB2V/OWxM87sf985Tkx3qFn4FEE5xLHABW8o1VksGCIkc=,iv:KYcvpeqmebIA79QAOS8tTBF4PRQhETi5lXTLWYIQDoo=,tag:l1Nt/VtRR5yBXrKh4c9lUw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
