apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:sG5/PxhSKfAeueTli+aqlBM7m6h7ZyQ85Fla+YBVg16rIhm0DJpDSA==,iv:AAfzEJVf8iV5n8azKG8/24ukRmXWwKyV2mDPb4+Bq+Q=,tag:NZt1LviLNpcjvUPL6ZbN6A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19ufzusf8ls394p4kl5498myl24w7x6ggc5w9grq4tk8dcyh709ls6ku97r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXZFdLMUl1ZDhhWjV6NVVX
            VDdyU2RUT1VmWllsdXQ5ZmVqcld5d2pZWWpNCmc3V01CWXhWNnZNeUhGOXBKTlN5
            dmdoWnAxZ3ROMm9FR1VYRytaYzJpSlkKLS0tIE5WSzhQU1E0aHJidHdGQW1wZFhm
            ZWYvd0xCQmVwK2hNTHYxY3JVN0VDakkKDHYfLN9pV393yg6xm9nkfVMo1olaLtFj
            5rGgbMPfPEc/7hJC3D/vCwIb2eXiE/YXRS/M15TwpBrCPfjlLUptNw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-04-14T13:33:05Z"
    mac: ENC[AES256_GCM,data:so7vCimNjozL3b7UqOVrhjtKzLLfUWipsd8EjPt8cBQw3X7GFnaLiGeUxpfi/smJFD3ix7VvWVBlT+DmKoojXAx189UEbiANgRc2OyS2IJ1sVDw2QgCwS1QJq6hUzCTZXMOAOfNoOTNj8qUomh/46EeB9ZxKuAfYX97UuWAkuIM=,iv:bpKHp9xvtwXEna9ajhvoBD8saExC9DEBreXKPSJSVdQ=,tag:whqTbAWYzoy0+kAGc5ezFQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
