apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:e9ijzA/XyReut7JwLyhFRBM4aeUSvwXmvOajsLVUzcqGM3OWc0LLBA==,iv:5NSTcSmAWuVgjvIbMQ2uk8Ypyrlho5Jmcij9y2vhhdk=,tag:jIljD2HajOxKf+8UBl0jiA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19ufzusf8ls394p4kl5498myl24w7x6ggc5w9grq4tk8dcyh709ls6ku97r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFV3l6cjBZcUxPSWRpQnkx
            dTlBZ0JFZ2Z4cDlFcUZiUndzV1VLZ2F5RFZrClRPbTlXSmpFTEZIcEkzM05JMlNI
            SDVrbXhaVzcvY1BFZE5jd041dXpTWlEKLS0tIGNpZmlId1kxWDBHamVYdXlLSE5z
            Ukd4MERiMmgreTJDWnBaUzJlek10SlkKD5a2Mh+EENvwymPffGr0OVFPBdCgXAxq
            qa/HrJNS/W4zhoEgs6z5IZJ1V1m/M5S8WiP+MxvV/98Ieax+m31rRA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-04-14T20:25:03Z"
    mac: ENC[AES256_GCM,data:zScXEbUfEt9EVsbh+5zqWfJbeqriMwA6SWVq8g2HmaxD2qifgZhZtPhgaY41Ylhlswasb/LICUo4xgTUkHIPvaHmYj3s25eEvzqRf6ML+oPs7AKk/73oMqrwC9wp7i2RKJgIqb+J3QiefGH8bgFcOu/UdayKUbmMEWu9JSPlTjI=,iv:swqLzytZstkjPmpsCYP2w+dXC/gKB7UPYsnQlqE4GEg=,tag:PVJCPBJG/nfUli2AkLVqSA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
