---
apiVersion: upgrade.cattle.io/v1
kind: Plan
metadata:
  name: talos
spec:
  version: ${TALOS_VERSION}
  concurrency: 1
  postCompleteDelay: 2m
  exclusive: true
  nodeSelector:
    matchExpressions:
      - key: feature.node.kubernetes.io/system-os_release.ID
        operator: In
        values: ["talos"]
  secrets:
    - name: system-upgrade-controller
      path: /var/run/secrets/talos.dev
      ignoreUpdates: true
  serviceAccountName: system-upgrade-controller
  upgrade:
    image: ghcr.io/jfroy/tnu:0.4.3
    envs:
      - name: NODE_IP
        valueFrom:
          fieldRef:
            fieldPath: status.hostIP
    args:
      - --node=$(NODE_IP)
      - --tag=$(SYSTEM_UPGRADE_PLAN_LATEST_VERSION)
