---
apiVersion: upgrade.cattle.io/v1
kind: Plan
metadata:
  name: talos-proxmox
spec:
  version: ${TALOS_VERSION}
  serviceAccountName: system-upgrade
  secrets:
    - name: talos
      path: /var/run/secrets/talos.dev
      ignoreUpdates: true
  concurrency: 1
  exclusive: true
  nodeSelector:
    matchExpressions:
      - key: feature.node.kubernetes.io/system-os_release.ID
        operator: In
        values: ["talos"]
      - key: feature.node.kubernetes.io/system-os_release.VERSION_ID
        operator: NotIn
        values: ["${TALOS_VERSION}"]
      - key: kubernetes.io/hostname
        operator: In
        values:
          - kube-proxmox-01
          - kube-proxmox-02
          - kube-proxmox-03
  tolerations:
    - key: CriticalAddonsOnly
      operator: Exists
    - key: node-role.kubernetes.io/control-plane
      operator: Exists
      effect: NoSchedule
  prepare: &prepare
    image: ghcr.io/siderolabs/talosctl:${TALOS_VERSION}
    envs:
      - name: NODE_IP
        valueFrom:
          fieldRef:
            fieldPath: status.hostIP
    args:
      - --nodes=$(NODE_IP)
      - health
      - --server=false
  upgrade:
    <<: *prepare
    args:
      - --nodes=$(NODE_IP)
      - upgrade
      - --image=factory.talos.dev/installer/88d1f7a5c4f1d3aba7df787c448c1d3d008ed29cfb34af53fa0df4336a56040b:$(SYSTEM_UPGRADE_PLAN_LATEST_VERSION)
      - --preserve=true
      - --wait=false
