---
# yaml-language-server: $schema=https://k8s-schemas.bjw-s.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &appname plex-auto-languages
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *appname
  interval: 1h
  timeout: 5m
  path: "./kubernetes/apps/media/plex-auto-languages/app"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  wait: false
  dependsOn:
    - name: volsync
      namespace: system
  components:
    - ../../../../components/volsync
    - ../../../../components/keda/nas-nfs-scaler
  postBuild:
    substitute:
      APP: *appname
      VOLSYNC_CLAIM: plex-auto-languages-config
      VOLSYNC_CAPACITY: 100Mi
      VOLSYNC_CACHE_CAPACITY: 100Mi
