---
# yaml-language-server: $schema=https://k8s-schemas.bjw-s.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &appname plex
  namespace: &namespace media
spec:
  targetNamespace: *namespace
  commonMetadata:
    labels:
      app.kubernetes.io/name: *appname
  interval: 1h
  timeout: 5m
  path: "./kubernetes/apps/media/plex/app"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  wait: false
  dependsOn:
    - name: onepassword-store
      namespace: external-secrets
    - name: volsync
      namespace: system
  components:
    - ../../../../components/volsync
    - ../../../../components/keda/nas-nfs-scaler
  postBuild:
    substitute:
      APP: *appname
      VOLSYNC_CLAIM: plex-config
      VOLSYNC_CAPACITY: 10Gi
      VOLSYNC_CACHE_CAPACITY: 5Gi
---
# yaml-language-server: $schema=https://k8s-schemas.bjw-s.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &appname plex-image-cleanup
  namespace: &namespace media
spec:
  targetNamespace: *namespace
  commonMetadata:
    labels:
      app.kubernetes.io/name: *appname
  interval: 1h
  timeout: 5m
  path: "./kubernetes/apps/media/plex/plex-image-cleanup"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  wait: false
  dependsOn:
    - name: onepassword-store
      namespace: external-secrets
  postBuild:
    substitute:
      APP: *appname
