---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/refs/heads/main/cert-manager.io/certificate_v1.json
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "aresu-eu"
spec:
  secretName: "aresu-eu-tls"
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "aresu.eu"
  dnsNames:
    - "aresu.eu"
    - "*.aresu.eu"
