---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/nfd.k8s-sigs.io/nodefeaturerule_v1alpha1.json
apiVersion: nfd.k8s-sigs.io/v1alpha1
kind: NodeFeatureRule
metadata:
  name: nordic-nrf52840-device
spec:
  rules:
    - # Nordic Semiconductor ASA nRF528xx OpenThread Device
      name: nordic.nrf52840
      labels:
        nordic.feature.node.kubernetes.io/nrf52840: "true"
        openthread.feature.node.kubernetes.io/present: "true"
      matchFeatures:
        - feature: usb.device
          matchExpressions:
            vendor: { op: In, value: ["1915", "cafe"] }
