---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - https://github.com/intel/xpumanager//deployment/kubernetes/daemonset/base/?timeout=120&ref=v1.3.2
  - https://raw.githubusercontent.com/intel/xpumanager/refs/tags/V1.2.39/deployment/kubernetes/monitoring/service-intel-xpum.yaml
  - https://raw.githubusercontent.com/intel/xpumanager/refs/tags/V1.2.39/deployment/kubernetes/monitoring/servicemonitor-intel-xpum.yaml
patches:
  - patch: |
      - op: add
        path: /spec/template/spec/nodeSelector/intel.feature.node.kubernetes.io~1gpu
        value: "true"
      - op: add
        path: /spec/template/spec/nodeSelector/node.kubernetes.io~1virtual
        value: "false"
    target:
      kind: DaemonSet
  - patch: |
      - op: remove
        path: /spec/namespaceSelector
      - op: add
        path: /spec/fallbackScrapeProtocol
        value: PrometheusText0.0.4
    target:
      kind: ServiceMonitor
